### ISSUE TITLE
Animations like ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by slonoed** [tonsky/rum#101]
Hi Nikita!
Do you have examples or suggestions how to implement animations? React has ReactCSSTransitionGroup for this kind of issues. Should I reimplement it, or maybe you know working solution. Regards.

**Comment by tonsky** [comment]
Best I’ve got for you:

https://gitter.im/tonsky/rum?at=57fd57d9dfe82a365b19151d

> just a quick update regarding adding animations, trickiest part from my perspective was to actually create the ReactCSSTransitionGroup the right way, since it seems an additional call to createFactory is needed (also note that it is CSSTransitionGroup in-code, not ReactCSSTransitionGroup as one might expect). Got it working like this: (def css-transition-group (.createFactory js/React (.. js/React -addons -CSSTransitionGroup)))

**Comment by ghost** [comment]
Hi! You can use ReactCSSTransitionGroup:

``` clojure
(ns blablabla
  (:require ; ...
            [sablono.core :as html :refer-macros [html]]
            [rum.core :as rum]))

(defn css-trans-group [options & elements]
  (let [f (js/React.createFactory js/React.addons.CSSTransitionGroup)]
    (f (clj->js options) (html elements))))

(rum/defc component [state]
  (css-trans-group
    {:transitionName "audit-popup"  ; options for ReactCSSTransitionGroup
     :transitionEnterTimeout 500
     :transitionLeaveTimeout 500}
... ; elements
     ))
```

In `project.clj`:

``` clojure
[rum "0.9.0" :exclusions [cljsjs/react cljsjs/react-dom]]
[cljsjs/react-dom "15.1.0-0" :exclusions [cljsjs/react]]
[cljsjs/react-dom-server "15.1.0-0" :exclusions [cljsjs/react]]
[cljsjs/react-with-addons "15.1.0-0"]
```

**Comment by slonoed** [comment]
@linuccio thank! It works perfect!
