### ISSUE TITLE
Server vs client rendering of keyword attributes

### ISSUE THREAD

**Issue by fotoetienne** [tonsky/rum#102]
Client rendering converts keyword attributes to string without the colon. Server rendering includes the colon.

    (client) d="13"><input type="text" name="x" place
    (server) d="13"><input type=":text" name="x" plac

Code to reproduce:

    [:input.totm-input
        {:type :text
         :name :x
         :placeholder "default"}]

**Comment by tonsky** [comment]
You’re not supposed to do that, really. Use strings

**Comment by fotoetienne** [comment]
Fair enough.
