### ISSUE TITLE
Support Server Side in cljs

### ISSUE THREAD

**Issue by yeehaa123** [tonsky/rum#105]
Currently, server-side rendering is only supported from clj/cljc. It would be great if it would also work on node / cljs. This way, it could, for instance, be used to render from aws lambda functions. Do you consider offering this feature?

**Comment by tonsky** [comment]
I believe you can do that by simply calling `(js/ReactDOMServer.renderToString (my-comp))`. Don’t forget to add `[cljsjs/react-dom-server "15.4.0-0"]` to deps. Is that what you’ve been looking for?

**Comment by yeehaa123** [comment]
Sorry for my late reply. Unfortunately, I cannot get this to work. When running on node, rum keeps complaining about a missing react dependency. Adding in, through cljsjs or npm or both, does not solve the problem. (possibly related to #113)

Also, I believe it would be nice if rum offers a consistent api for serverside rendering independent of the platform. Falling back on js/ReactDomServer feels dirty ;-). 

Happy to help out with this one, just not quite sure where to start

**Comment by dijonkitchen** [comment]
Looks like #113 has been fixed, is this still an issue?

**Comment by roman01la** [comment]
I don't think bootstrapped compiler support is the problem here, more likely an issue with dependencies. I'll look into this later.
