### ISSUE TITLE
ESI Support

### ISSUE THREAD

**Issue by jjl** [tonsky/rum#106]
I'm not sure to what degree react makes this difficult, but it would be nice to be able to insert ESI tags.

The only method I can come up with is `:dangerouslySetInnerHtml`, is there something i'm missing?

**Comment by chpill** [comment]
Integrating ESI and react on the server is nearly impossible sadly...

The thing is, react (and its clojure implementation in the rum server-side rendering code) associates ids to every DOM nodes its creates, and then makes a checksum of the whole tree. The checksum generated on the server needs to be correct for react (in the browser this time) to reuse the markup from the server

Working with ESI means rendering subtrees, so each of these subtrees will have its own ids and checksum. When Varnish (or any other cache that deals with ESI tags) recompose the page from the different subtrees, the checksum on the real react root cannot be the right one, and the browser client react will not reuse the markup... For a more detailed explanation of the problem, see this question I asked on reddit some month ago about this very issue https://www.reddit.com/r/reactjs/comments/4kudja/serverside_rendering_question/

To make it work, you would basically need to create a varnish extension that, after aggregating the subtrees from all esi tags, resets all the nodes react-ids and recalculate the checksum with the adler32 algorithm. I actually spent one evening trying to get something like that to work. I never finished it though, when you are trying to put some code in front of your http cache, It may be time to rethink the issue...

**Comment by tonsky** [comment]
Thanks @chpill for such a meaningful answer. Me, personally, never heard about ESI before, so I would have no idea :)

**Comment by jjl** [comment]
For non-ESI reasons, I've moved to generating static instead of React HTML. Like @chpill I can't really tell the difference and it gets rid of annoying warnings that I never could figure out (and jesus, react, if the doms are different, you could show a large enough snippet that I can diagnose why they're different...)

**Comment by roman01la** [comment]
@chpill I think this is not an issue anymore since React moved away from checksum and ids?

**Comment by chpill** [comment]
@roman01la Indeed, this is probably not relevant anymore.

**Comment by roman01la** [comment]
Good, closing then
