### ISSUE TITLE
"Schedules react component to be rendered on next animation frame" leads to issues in some cases

### ISSUE THREAD

**Issue by mogadanez** [tonsky/rum#107]
have control:
```
[:input.block-input.form-control
        {:placeholder "e.g. more-t-shirts"
         :value channel-name
         :required    true    
         :on-change #(swap! local-state assoc :channel-name (.. % -target -value))
         :autoFocus   true}]
```

typing in input leads RUM to  to request-render with follow stack

![image](https://cloud.githubusercontent.com/assets/790307/20939867/e40b9766-bbf0-11e6-85a5-b4e4109703d6.png)

since it goes to render Async from it,  when I type FAST in input it lead to replace value to previous one(s).
best reproduced in IE

**Comment by mogadanez** [comment]
looks similar with 
https://github.com/tonsky/rum/issues/86

**Comment by tonsky** [comment]
Yeah, I thought we’ve solved this one... What versions of Rum and Sablono are you using (check with `lein deps :tree` please)

**Comment by mogadanez** [comment]
```
 [rum "0.10.0"]
   [cljsjs/react-dom "15.1.0-0"]
   [cljsjs/react "15.1.0-0"]
   [sablono "0.7.2"]
```

**Comment by mogadanez** [comment]
updated to  
```
 [rum "0.10.7"]
   [cljsjs/react-dom "15.3.1-0"]
   [cljsjs/react "15.3.1-0"]
   [sablono "0.7.5"] 
```
but problem is still here

**Comment by mogadanez** [comment]
actually, currently i'm not sure that it cuts symbols, but it is  have serious performance issues when typing fast in IE

**Comment by tonsky** [comment]
You’ll need to provide a test project I can run to reproduce that. Are you
sure you don’t re-render your whole app on each keystroke?

**Comment by mogadanez** [comment]
Checked with `Painting  Flashing` option in Chrome. Definitely not re-render entire app( at least in chrome )

Will try to make sample but it take time.
I'm new to clojure stack, just got a project to support as Christmas gift from Grinch

**Comment by roman01la** [comment]
@mogadanez Is this still a thing?

**Comment by roman01la** [comment]
@mogadanez Please try to repro this in 0.12.0-SNAPSHOT and report any issues to #205

**Comment by mogadanez** [comment]
I'm not working with clojure  any more
throw it away as bad dream
