### ISSUE TITLE
Testing React components

### ISSUE THREAD

**Issue by ozmuir** [tonsky/rum#108]
I'm currently exploring React testing techniques as summarized in [Approaches to testing React components - an overview](http://reactkungfu.com/2015/07/approaches-to-testing-react-components-an-overview/), and cannot find an acceptably easy way to use an _advanced_ techniques like shallow rendering and event simulation provided by React Test Utils, since it requires raw React component to work on. I can mount Rum component into the DOM and inspect it with jQuery, of course, but would rather prefer Test Utils' methods. So the question is, is it possible to test Rum components _without_ mounting it into the DOM first? Is it possible, in a test run, to get the React component out of an arbitrary Rum component (even if it _does_ require rendering it into DOM)?

**Comment by tonsky** [comment]
To get React component form Rum one, use `(:rum/react-component state)`. You can get state in lifecycle methods or in render by using `defcs` (please consult the Readme). You can get React Elements (not components) without mounting, I thing that one is the same as in React. Any component you define with `defc` will return react element when invoked as a function.

Does that answer your question, @rielsi ?

**Comment by ozmuir** [comment]
Oh, I did not realized that calling Rum component as a function will produce a _pure_ React element. This makes things a lot easier. I think I'll have no problem using a returned element with React Test Utils and such.
I'm still missing a piece, however. Is it possible to extract React _component_ out of an arbitrary Rum component, being "outside" of it and not in a lifecycle method?
***
Anyway, it seems I can get React component via returned element's `type` property. Thank you, @tonsky, think we can close this for a while.

**Comment by tonsky** [comment]
That one is tricky. Couple of versions ago, that’s what `mount` would’ve
returned. But then, following React team guidelines, I learned that it’s
not a good way to reference the component (pure components would not return
instance on mount, and in Rum difference between pure/non-pure is
implicit). So now `mount` always returns nil. The recommended way would be
to use `with-ref` and use a “callback ref” (ref=fn, not string) and in that
callback somehow send component ref where you need it

**Comment by ozmuir** [comment]
Thank you, `with-ref` works just fine. Good to know it _is_ the recommended way, better be sure I'm using the right tool... I also found I have no need for a component's _class_, actually, to test component's rendered structure with `enzyme`; having React _element_ is enough.
