### ISSUE TITLE
Rum & dynamic bindings

### ISSUE THREAD

**Issue by OliverM** [tonsky/rum#109]
Do Rum components work with ```(def ^:dynamic ...)``` and ```(binding ...)```? I'm trying to dynamically bind an event source based on whether I'm in development or production, and invoking functions in Rum components that are in turn being invoked under a ```(binding ...)``` invocation aren't working (they're retaining their original values). 

Normal clojurescript functions are using the new binding as expected. Is this something anyone knows outright won't work with Rum? I can post detailed code if necessary!

**Comment by martinklepsch** [comment]
`binding` in ClojureScript only works with fully synchronous code. So while it may work for an initial render any dynamic bindings are lost in code that is ran later (e.g. Event handlers) 

I'm on mobile right now but if you google "cljs dynamic binding" (maybe also try with "async") you should find some more context...

**Comment by OliverM** [comment]
Thanks for the pointer @martinklepsch! Thought clojure was trolling me for a bit there.

Came across one proposal that looks promising as a workaround:
https://github.com/binaryage/cljs-zones
