### ISSUE TITLE
How to integrate a React component from a library?

### ISSUE THREAD

**Issue by alvatar** [tonsky/rum#110]
I've been trying to integrate these components with no luck:

https://github.com/react-component/slider
https://github.com/mpowaga/react-slider (with the cljsj version https://github.com/cljsjs/packages/tree/master/react-slider)

I suppose there is a specific way of doing it, since this seems a natural thing to do. Is this the case? Can any of these sliders be integrated in a relatively straight-forward way?

**Comment by tonsky** [comment]
Add to project.clj:
```
:dependencies [[cljsjs/rc-slider "4.0.1-0"]]
```

Add to namespace:
```
(ns ...
 (:require ...
   [cljsjs.rc-slider]))
```

Then just

```
(rum/defc slider []
  (js/React.createElement js/Slider #js { :min 0
                                          :max 100
                                          :range true
                                          :defaultValue #js [40 60] }))
```

Don’t forget to include CSS https://github.com/react-component/slider/blob/master/assets/index.less otherwise you won’t see anything.

Please let me know if that helps and we can close this issue

**Comment by alvatar** [comment]
It does work. Thank you!
