### ISSUE TITLE
`Can only update a mounted or mounting component` when using Material UI component

### ISSUE THREAD

**Issue by alvatar** [tonsky/rum#111]
I'm using https://github.com/madvas/cljs-react-material-ui with Rum, and it's been usually working well, but I've encountered this issue with the Slider component. It produces the following error:

```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Slider.getTrackOffset (material-ui.inc.js:53885)
    at material-ui.inc.js:53918
getTrackOffset @ material-ui.inc.js:53885
(anonymous) @ material-ui.inc.js:53918


Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Slider component.
printWarning @ material-ui.inc.js:1297
warning @ material-ui.inc.js:1321
getInternalInstanceReadyForUpdate @ material-ui.inc.js:17264
enqueueSetState @ material-ui.inc.js:17416
ReactComponent.setState @ material-ui.inc.js:1780
onDragStop @ material-ui.inc.js:53929
Slider._this.handleMouseEnd @ material-ui.inc.js:53745
```

```clojure
(def ui-values (atom {:val 500}))

(rum/defc mycomp < rum/reactive []
  (ui/mui-theme-provider
   {:mui-theme (get-mui-theme {:palette {:text-color (color :blue900)}})}
   [:div [:p (:val (rum/react ui-values))] ; <-- actually now fails even with this removed
    (ui/slider {:min 200 :max 20000
                :value (:val (rum/react ui-values))
                :on-change #(swap! ui-values assoc :val %2)})]))

(rum/mount (mycomp) (js/document.getElementById "app"))

```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet" type="text/css">

  </head>
  <body>
    <div id="app"></div>
    <script src="js/compiled/main.js" type="text/javascript"></script>
  </body>
</html>
```

**Comment by uaalto** [comment]
Seems like a way to solve it is to add some flag and modify it with a `did-mount` custom mixin.
I'd like to avoid this if the issue can be fixed in a cleaner way. Any pointer on this one @tonsky ?

**Comment by tonsky** [comment]
There’s an example here: https://github.com/madvas/cljs-react-material-ui#using-with-rum
Are you sure you’re requiring exactly `[cljs-react-material-ui.rum :as ui]`?
Could you create a full github project that I can clone?

**Comment by alvatar** [comment]
Hi @tonsky .
Yes, that is the minimal example I started with. I've been using both projects for a while now. It happens only with the slider. Here you have a complete minimal version:
https://github.com/alvatar/rum-material-ui

Thank you for looking into it!

**Comment by tonsky** [comment]
This project is empty

**Comment by alvatar** [comment]
Sorry, wrong gitignore. Fixed and pushed.

**Comment by tonsky** [comment]
As far as I can tell, it’s the problem in `cljs-react-material-ui`. In [adapt-rum-class](https://github.com/madvas/cljs-react-material-ui/blob/master/src/cljs_react_material_ui/core.clj#L23-L32) they actually create new react class every time component is rendered. Which is probably not what everybody expects (React, Slider, Material UI)

But it sort of work if you remove `ui/mui-theme-provider` call from `mycomp` and leave the one that is called in `app`.

Still, I’d suggest that `cljs-react-material-ui` should be fixed. What they do is very-very wrong :)

**Comment by tonsky** [comment]
Closing in favour of https://github.com/madvas/cljs-react-material-ui/issues/25

**Comment by alvatar** [comment]
Thanks for looking at this @tonsky. Awesome work with Rum, I like it the best among the React adapters! :+1:

**Comment by alvatar** [comment]
Re: removing `ui/mui-theme-provider` from the inner element doesn't work in my real app, where I only have an instance of the element, so cljs-react-material needs to be fixed to be usable.
Thanks again!
