### ISSUE TITLE
did-remount should be will-remount

### ISSUE THREAD

**Issue by tonsky** [tonsky/rum#118]

**Comment by roman01la** [comment]
@tonsky Do you remember what's the motivation for this change?

**Comment by tonsky** [comment]
It just needs a better name. It is analogous to `componentWillReceiveProps`. It used to be called `transfer-state`, but then I changed semantics and had to change name too, I guess.

It happens before `should-update`, `will-update` etc, so it should be `will-*` I guess. Or something similar to `transfer-state` sounds good to me too.
