### ISSUE TITLE
server side render inconsistency: excessive space in class when set as attribute list

### ISSUE THREAD

**Issue by altV** [tonsky/rum#119]
[:a.hi {:class [nil]}] gives
`<a class="hi ">` in server case, and
`<a class="hi">` on client. (or maybe vice versa)

**Comment by tonsky** [comment]
Description is broken. Maybe a duplicate of #104 though

**Comment by altV** [comment]
oops. patched

**Comment by altV** [comment]
looks like a duplicate. will bump my version from 0.10.7 to 0.10.8 and retest, but changelog doesn't tell about this one

**Comment by tonsky** [comment]
It’s because it’s only partially fixed :)

**Comment by roman01la** [comment]
Closing, because it's a duplicate.
