### ISSUE TITLE
ClojureScript 0.0-2727 and sablono 0.3.x

### ISSUE THREAD

**Issue by peeb** [tonsky/rum#12]
The latest version of `sablono` now depends on `[cljsjs/react]` which breaks `rum` in avanced compilation mode whilst it still depends on `[com.facebook/react]` (because there are two competing `externs` files).

Would you be interested in a pull request that updates the codebase to depend on `[sablono "0.3.1"]` and `[cljsjs/react "0.12.2-5"]` and the new foreign libraries features of ClojureScript?

This has the addiontal benefit that you no longer need both `index.html` and `web/dev.html` since all optimization levels now work with the same template.

**Comment by tonsky** [comment]
Sure, can you do it?

**Comment by peeb** [comment]
Yes. I'm just doing it now.

**Comment by peeb** [comment]
Pull request #13
