### ISSUE TITLE
server side render inconsistency: wrong rendering of keyword values of attributes on server 

### ISSUE THREAD

**Issue by altV** [tonsky/rum#120]
`[:input {:type :checkbox}]` is rendered
`<input type=":checkbox">` on server, while correctly
`<input type="checkbox">` on client

**Comment by tonsky** [comment]
description is broken

**Comment by altV** [comment]
+patched here

**Comment by roman01la** [comment]
I'd say the server rendering is wrong here, it's common to write down values as keywords, for example to have better autocompletion in your IDE.
