### ISSUE TITLE
Inconsistent Class Name Rendering in Server vs. Client

### ISSUE THREAD

**Issue by jupl** [tonsky/rum#121]
I saw some other issues possibly related but I figure I would open a new one since it's a bit of a different use case. This was tested on 0.10.8. Let's say I have this template:

```clj
(rum/defc something []
  [:div {:class (:container #?(:clj (:map style) :cljs style))}
    ;; ...
```

Server-side rendering renders as expected:

```html
<div class="container-x" ...
```

However, the client side renders the following:

```html
<div class="container :container container-x" ...
```

Currently the workaround to this is I have to write something like this so the client renders identical to the server:

```clj
(rum/defc something []
  (let [x (:container #?(:clj (:map style) :cljs style))]
    [:div {:class x}
      ;; ...
```

**Comment by tonsky** [comment]
This is probably an artefact of Sablono precompilation. Try reporting to https://github.com/r0man/sablono

**Comment by roman01la** [comment]
@jupl Is this still a thing?

**Comment by roman01la** [comment]
Can't repro on current master, closing.
