### ISSUE TITLE
Coming from React.js, how to handle custom component API ?

### ISSUE THREAD

**Issue by DjebbZ** [tonsky/rum#126]
Hello,

I'm an experienced React.js developer discovering rum. In React.js world, we're used to attach custom behaviour method to a component and freely call it. Like this (omitted `this` js weirdness) :

``` js
class MyComponent extends React.Component {
    constructor(props) {
        super(props);
        this.state = { counter: 0, interval: null };
    }
    componentDidMount() {
         const intervalId = setInterval(() => this.increment(), 1000);
         this.setState({ interval: intervalId })
    }
    componentWillUnmount() {
        this.stopIncrementing();
    }
    stopIncrementing() {
        clearInterval(this.state.interval);
        this.setState({ interval: null });
    }
    increment() {
         this.setState({ counter: this.state.counter++ });
    }
    render() {
        return (
            <div>
                <p>{this.state.counter} times<p>
                <button onClick={this.stopIncrementing}>Stop incrementing</button>
            </div>
        );
    }
}
```

When trying something similar in rum, I have difficulties attaching a named behaviour method to the component. To be precise, here `stopIncrementing` is called at the same time in the `render` and in a lifecycle hook (`componentWIllUnmount`). This single method has free and easy access to state (or props/context if necessary).

In rum, when I did attach a similar custom method using `:class-properties`, I ended up doing some trickery to retrieve and manipulate the state, which wasn't even the atom I created in the `:init` hook, but the volatile rum creates internally. So the state is in a weird "data-type" (volatile instead of atom), and the method hard to expose and reuse in the render.

I'd love some guidance on this point. Maybe I'm not doing idiomatic rum and trying to force my mental "javascript" model of React into rum. It would have been easy if the problem was just data-based ("just use an atom and react to it"), but in this case where you have to side-effects that are inherently non data-based I feel rum is a bit lacking, or I'm missing something.

Thanks in advance !

**Comment by akovantsev** [comment]
@DjebbZ have a look at
https://github.com/tonsky/rum/blob/gh-pages/examples/rum/examples/custom_props.cljs

**Comment by akovantsev** [comment]
something like this (a bit too verbose, so you could adjust to your actual requirements easier):
```clojure
(rum/defcs counter
  < (let [k ::interval
          stop! (fn [state]
                  (js/clearInterval (get state k))
                  (dissoc state k))]
      {:will-mount
       (fn [state]
         (let [counter (atom 0)
               callback #(swap! counter inc)
               interval (js/setInterval callback 1000)
               component (:rum/react-component state)]
           (add-watch counter ::counter
             (fn [_ _ _ _]
               (rum/request-render component)))
           (assoc state
             k interval
             ::counter counter
             ::stop! stop!)))

       :will-unmount
       (fn [state]
         (stop! state))})
  [state]
  (let [v @(::counter state)
        stop! #((::stop! state) state)]
    [:div (str v " times")
     [:button {:onClick stop!} "stop"]]))
```

**Comment by DjebbZ** [comment]
Thanks, but it doesn't cut it. As I was saying just now in Gitter, the problem is that in the custom method when I want to access the internal state of the component I set in the `:init` hook, I end retrieving the internal volatile rum uses.

My real use case is to create a product viewer that "rotates" every few ms and stop rotating when hovering. "Rotating" really means displaying another image. The code looks like this (cleaned-up) :

``` cljs
; helper TODO: Contribute to rum ;)
(defn rum-props
  "Retrives a custom prop set with :class-properties."
  [state key]
  (aget (:rum/react-component state) (clj->js key)))

(def rotate-360-mixin
  {:class-properties {:start-rotation! (fn start-rotation! []
                                         (this-as comp
                                           (let [rum-state (rum/state comp)
                                                 img-idx (::img-idx @rum-state)
                                                 callback #(do
                                                             (swap! img-idx inc)
                                                             (rum/request-render comp))
                                                 interval (js/setInterval callback 1500)]
                                             (vswap! rum-state #(assoc % ::interval interval)))))
                      :stop-rotation!  (fn stop-rotation! []
                                          (this-as comp
                                            (let [state (rum/state comp)]
                                              (js/clearInterval (::interval @state))
                                              (vswap! state #(dissoc % ::interval)))))}
   :init             (fn [state]
                       (assoc state ::img-idx (atom 0)))

   :did-mount        (fn [state]
                       (let [start-rotation! (rum-props state :start-rotation!)]
                         (start-rotation!)
                         state))

   :will-unmount     (fn [state]
                       (let [stop-rotation! (rum-props state :stop-rotation!)]
                         (stop-rotation!)
                         state))})


(rum/defcs viewer360 < rotate-360-mixin
  [state base-img-url]
  (let [images-list () ; ... business here
        img-idx (deref (::img-idx state))
        stop-rotation! (rum-props state :stop-rotation!)]
    [:img {:src            (str (urls/get-product-media-base-url)
                                (get images360 img-idx))
           :on-mouse-enter stop-rotation!}]))
```

Problems : 
- accessing custom method in render feels weird (even with my helper)
- custom method requires some trickery to access and manipulate the state

**Comment by DjebbZ** [comment]
Didn't see your comment @akovantsev, let me read it...

**Comment by DjebbZ** [comment]
Never thought of a `let` binding between the component name and the actual mixin map. Good idea ! Gonna try right now and let you know.

**Comment by akovantsev** [comment]
@DjebbZ 
```clojure
(rum/defcs counter
  < {:will-mount
     (fn [state]
       (let [counter (atom 0)
             hovering? (atom false)
             callback #(when-not @hovering?
                         (swap! counter inc))
             interval (js/setInterval callback 1000)
             component (:rum/react-component state)]
         (add-watch counter ::counter
           (fn [_ _ _ n]
             (rum/request-render component)))
         (assoc state
           ::interval interval
           ::counter counter
           ::hovering? hovering?)))

     :will-unmount
     (fn [state]
       (js/clearInterval (::interval state))
       state)}
  [state]
  (let [v @(::counter state)
        h? (::hovering? state)
        pause!  #(reset! h? true)
        resume! #(reset! h? false)]
    [:div {:onMouseEnter pause!
           :onMouseOut resume!
           :style {:width "50px" :height "50x"}}
     (str v " (hover me)")]))
```

**Comment by DjebbZ** [comment]
I don't need the resume feature but it's pretty clever : just use data. BTW, your previous solution works wonderfully. Many thanks !

**Comment by DjebbZ** [comment]
To be honest I just included the resume functionality as it might reveal useful.

To sum up the solution for other fellow javascripters (or anyone really) : 
- just store the useful state in rum `state`
- react to it by watching the relevant atom
- declare your component API in the render function in the `let` binding which simply manipulate the state.

No idea how it scales for very complex stuff, but at least it worked very well for me.

Thanks again !

**Comment by martinklepsch** [comment]
Just a minor note: there's `add-watch` and `remove-watch` — to ensure proper clean up of resources you'll need to remove added watches when unmounting a component. :)

**Comment by DjebbZ** [comment]
I was wondering this just now. So watches don't get cleaned up and garbage collected magically ! Thx.

Also wondering if replacing manual watches with the `reactive` mixin is better. It would feel more `rum-y`, no ?

**Comment by akovantsev** [comment]
@martinklepsch 
`rum/local` does not clean up its watcher, so didn't do I:
https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.clj#L165-L169
https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.cljs#L242-L255

**Comment by akovantsev** [comment]
@DjebbZ in this case I used atom local to component, because it makes little sense to store "is hovering over this particular div" in some external atom. But usually, when you just need to render some "db" data, you'd use either `rum/reactive` or `rum/static` to reduce boilerplate, and state external to component is easier to persist.

**Comment by DjebbZ** [comment]
Makes perfect sense. I'm happy I found you at the right moment as you're very helpful.
