### ISSUE TITLE
:style maps kebab-case to CamelCase automatic conversion only works with literals?

### ISSUE THREAD

**Issue by xavi** [tonsky/rum#127]
When having something like

```
[:div {:style (merge {:margin-left "2rem"}
                      (when focused? {:color "red"}))}]
```

The browser shows

```Warning: Unsupported style property margin-left. Did you mean marginLeft?```

This doesn't happen when the style is a map literal instead of the result of a `merge`.

Is it a bug? In Rum or in Ŝablono?

**Comment by martinklepsch** [comment]
This is Sablono related. Probably best to move this issue to the sablono
project. 👍

**Comment by xavi** [comment]
👍 Moving it there (https://github.com/r0man/sablono/issues/158) and closing this.
Thanks!
