### ISSUE TITLE
How to optimize for Closure dead code removal?

### ISSUE THREAD

**Issue by zlorf** [tonsky/rum#128]
My rum-using code is compiled into two different files, targeting different use cases via some compile-time constants.
Closure compiler is quite good at removing the dead (unused) code, so these two files contain only function they need.
However, that is not the case with rum components. Even when they are not used, they don't get trimmed away because of the way they are declared.
Let's see. These are two components that are not used anywhere (except `test-component2` in `test-component`):

```clojure
(rum/defc test-component2 []
  [:div.test-component2 "TEST COMP2"])

(rum/defc test-component []
  [:div.test-component "TEST COMP" (test-component2)])
```

This gets compiled into:
```javascript
l$=function(){var a=rU(function(){return React.createElement("div",{className:"test-component2"},"TEST COMP2")}),b=mU(O.j(new J(null,1,5,K,[a],null),null),"test-component2");return Wd(function(a,b){return function(){function a(b){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new z(e,0)}return c.call(this,d)}function c(a){return uU(b,
tU(a))}a.A=0;a.B=function(a){a=w(a);return c(a)};a.o=c;return a}()}(a,b),new g(null,1,[br,b],null))}();

(function(){var a=rU(function(){var a=Z(l$.v?l$.v():l$.call(null));return React.createElement("div",{className:"test-component"},"TEST COMP",a)}),b=mU(O.j(new J(null,1,5,K,[a],null),null),"test-component");return Wd(function(a,b){return function(){function a(b){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new z(e,0)}return c.call(this,d)}function c(a){return uU(b,tU(a))}a.A=0;a.B=function(a){a=w(a);return c(a)};a.o=c;return a}()}(a,
b),new g(null,1,[br,b],null))})();
```

As you can see, the Closure compiler has detected that the `test-component` is not used anywhere, so it didn't assign a return value to a var (like it did with `$l=` for the first component).
But the whole function call with component creation is left intact, yet unneeded.

Does anybody have an idea how to make Closure compiler remove those?
I've tried adding some hints to the extern file, yet they don't change anything:
```javascript
var rum;
/** @nosideeffects */
rum.core.element = function() {};
/** @nosideeffects */
rum.core.build_class = function() {};
/** @nosideeffects */
rum.core.render_state__GT_mixin = function() {};
/** @nosideeffects */
rum.core.args__GT_state = function() {};
```

I know I can wrap component declarations in `(when CONSTANT (rum/defc ...))`, but that require tracking down whole components call stack.

**Comment by martinklepsch** [comment]
That's an interesting observation and definitely should be addressed if true. Could you possibly provide a reproduction case as a runnable repo on Github?

And a side note: when debugging advanced builds it can be helpful to set `:pseudo-names` to true. This way variable names will not be shortened to `$l=` and instead stay in their long, more descriptive form.

**Comment by zlorf** [comment]
Here you go: https://github.com/zlorf/rum-dead-components-demo

Initially I was testing rum 0.8.1, but the issue is still present with rum 0.10.8 (although compiled code is shorter and more readable).

**Comment by tonsky** [comment]
I’m not familiar with Closure’s dead code elimination. Why do you think it’s happening?

**Comment by zlorf** [comment]
Closure during compilation keeps track of what is being used and then trim out functions/variables that are not called/used.
Let's see compiled code:
```javascript
var $core$browser$test_component2$$ = $rum$core$build_defc$$(function(){return React.createElement("div",{className:"test-component2"},"SHOULD NOT BE PRESENT 2")}, "test-component2");
```
I'm not an expert on this, but it seems that for Closure, even if `$core$browser$test_component2$$` is not used, the `$rum$core$build_defc$$` call is preserved because it potentially may have some side effects. 

That is why I was trying to mark some functions as `@nosideeffects`, but either I don't know how to do it properly, or it just doesn't work.

**Comment by stephenbrady** [comment]
This is most likely because of the call to `with-meta` here: https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.cljs#L129

`with-meta` will prevent dead code elimination because that function potentially dispatches to a protocol method call (`-with-meta`) on the function's argument. You can see this for yourself by creating a namespace like so and compiling it:

```clojure
(ns foo)

(with-meta (fn []) {"bar" 1})
```
The anonymous function will not be dead code eliminated as it otherwise would (there is actually enough compile-time information to conceivably dead-code eliminate this specific example since it's a (function) literal, but the Closure Compiler doesn't go to that (extreme) length).

With regards to the no side effects annotation, it can only be applied to Closure externs:
https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nosideeffects-modifies-thisarguments

There could be other reasons why dead-code elimination is not happening, but taking a quick glance, I don't see anything else.

**Comment by zlorf** [comment]
Yeah, I've tried placing annotations in the extern file, not directly in the code.

I'll make a test today whether `with-meta` is the only issue.

**Comment by stephenbrady** [comment]
The nosideffect annotation isn't going to help you. It's intended to annotate code outside the scope of the Closure compiler. I'd just try patching rum by removing the call to with-meta and see if you get dead code elimination.

**Comment by zlorf** [comment]
I've just done it:
https://github.com/zlorf/rum-dead-components-demo/commit/32cbfa00cf915a068eddeb58c78a5a06a3b0ac93

(copied crucial fragments from `rum` and disabled `with-meta`)

No success.

(I've also tried with extern, with the same effect, but you've explained why it won't work)

**Comment by rauhs** [comment]
So I spent too much time to not comment with my findings:
Fun fact:
```clojure
(concat [] ["SEARCH_ME!"])
```

doesn't get DCE'd. :/

The culprit is definitley `rum.core/build-class`. There are a few candidates that prevent DCE. One obvious one is this one:

```clojure
(reduce #(%2 %1) render wrap-render)
```

Notice how it calls functions that were passed. Unless GCC understands all the code, it can't possibly get to the conclusion that all those `%2` function invocations are all side-effect free. But even trying to tweak this there is more code that GCC thinks has side effects.

One particular change that I have done locally is to do the component creation lazily ( https://github.com/tonsky/rum/wiki/Optimizations ). Ie wrap it in a `delay` which only gets realize upon first use of the component. Does completely get DCE'd (just checked) and it also improves startup time. Wouldn't change the rum API, so this is something for tonsky to consider...

**Comment by zlorf** [comment]
@rauhs , that is one clever idea, and in fact it is really working!
Proof: https://github.com/zlorf/rum-dead-components-demo/commit/3dc64143677ddc30a006870e9ef43596acde5382

**Comment by sansolovyov** [comment]
@rauhs I wonder if there are any downsides to using `delay`. Have you tried to measure if it makes first component call much slower? :)

**Comment by rauhs** [comment]
@piranha Well if I have 50 components, and on initial render 20 of them are needed and rendered. Then without delay 50 are initialized and then the mount happens. With the delay, 20 are initialized and mounted. So the initial render is strictly faster. (If we omit the overhead of a fn call). The deref is also pretty cheap. Though, we could also use `goog.functions.cacheReturnValue` instead of a `delay` to get some tiny, non-measurable speedup :)

**Comment by ducky427** [comment]
Observation as a new Rum user - this issue is quite serious as it prevents people from creating a component library with all possible components and then optimally using some components in their actual app.

**Comment by martinklepsch** [comment]
So @rauhs just to recap: we can fix this for all users without any breaking changes by introducing one of the [techniques described in the wiki](https://github.com/tonsky/rum/wiki/Optimizations)? 

If so would you be willing to create a PR that people can use to test? 

Maybe @tonsky can then also cut an `-alpha` release so others don't have to build locally. Or we try the (cool looking) [JitPack](https://lambdaisland.com/blog/17-05-2017-loading-clojure-libraries-directly-from-github).

**Comment by rauhs** [comment]
One issue/breakage would be this line:

https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.cljs#L119

Currently, this isn't documented API. Ie, getting the React Component Class from the meta data of the returned `MetaFn`. With the lazy creation you wouldn't get the `:rum/class` anymore.
Given the created MetaFn is unnecessary slowdown I'd say break it and provide a different API in case people actually want the created class (or let them create it themselves with making `rum/build-class` public API).

**Comment by martinklepsch** [comment]
Here are all [public usages of :rum/class](https://github.com/search?utf8=%E2%9C%93&q=%22%3Arum%2Fclass%22+extension%3Acljs+extension%3Acljc+extension%3Aclj&type=Code) on GitHub.

Doesn't seem super popular but then again this doesn't include private projects.

**Comment by rauhs** [comment]
Yeah we could also make it non-breaking by creating a meta fn out of the lazy constructor and specify a `-meta` protocol on it to return the meta of the built component:

```clojure
(extend-type MetaFn
  ICloneable
  (-clone [mfn] (MetaFn. (.-afn mfn) (.-meta mfn))))

(let [mfn (with-meta (fn []
                       "the-fn") nil)]
  (meta
    (specify mfn
      IMeta
      (-meta [_] "custom meta!!"))))
```

Needs the `-clone` which is missing by CLJS.

**Comment by rauhs** [comment]
There is actually a much easier and better way to do this properly:

```clojure
(let [bf #(build-component spec) ;; Avoid IIFE
          c (gf/cacheReturnValue bf)
          f (fn []
              (let [ctr (c)]
                (.apply ctr ctr (js-arguments))))]
      (specify! f IMeta (-meta [_] (meta (c))))
      f)
```

We can use `specify!` here and add `IMeta` to the function just like `with-meta` would do but still avoid doing the initialization until it's actually needed.

This also DCE's and shouldn't break anything.

**Comment by martinklepsch** [comment]
@rauhs do you want to provide a PR for this change? maybe @tonsky can then cut a pre-release and interested folks can give it a spin.

**Comment by rauhs** [comment]
@martinklepsch I'm sorry. For different reasons, I won't be able to do a PR anytime soon.

**Comment by martinklepsch** [comment]
@rauhs well no problem, I'll try to make a PR and credit you accordingly. :) Hope all is well in the meantime :)

**Comment by zlorf** [comment]
@rauhs @martinklepsch I've just tested your proposition and using `specify!` prevents DCE. Wasn't your observation the same?

**Comment by rauhs** [comment]
I have this working on my own little fork and it works there. Though I won't have to time to try this on rum proper. What helped: You need to break the `specify` out in a separate fn and then DCE seems to work again. Something like:

```clj
(defn component-invoker
  [c]
  (let [f (fn f []
            ...)))]
    (specify! f
      IMeta
      (-meta [x]
          (meta (c)) )))
    f))
(defn component
  ([spec]
   (let [bf #(build-component spec) ;; Avoid IIFE
         c (gf/cacheReturnValue bf)]
     ;; Done like this to allow DCE!
     (component-invoker c spec))))
```
I also added `-deref` proto to the fn which returns the React class. (this makes interop much nicer than `(:rum/class (meta x))`)

Sometime should test his.

**Comment by zlorf** [comment]
Well, I applied this solution (precisely: @martinklepsch code) in https://github.com/zlorf/rum-dead-components-demo/commit/d43e8647dd21bdc5b4443c03ae7cb26a402a067d and compiled code still contains `SHOULD NOT BE PRESENT`. But when I remove `specify!` call, then DCE happens.

**Comment by rauhs** [comment]
@zlorf Upgrade your CLJS compiler to 1.9.946 and it seems to work for me.

**Comment by zlorf** [comment]
@rauhs Thanks a lot, that was indeed a solution.
