### ISSUE TITLE
React.createClass is deprecated starting with React v15.5.4

### ISSUE THREAD

**Issue by roman01la** [tonsky/rum#130]
Starting with v15.5.4 React will output warning about `React.createClass` being deprecated. `React.Component` should be used instead. Looks like Sablono already migrated to `React.Component` [here](https://github.com/r0man/sablono/blob/fb5d756c4201598fe8737ae2877e76f9c25a96f1/src/sablono/interpreter.cljc#L34).

**Comment by rauhs** [comment]
It'd also be possible to use `class extends React.Component` syntax and let the GCC do the conversion. Thought it'd need a `:language-in :ecmascript6` so not sure if it's a good idea. This is working: https://gist.github.com/rauhs/5ba042954b6e19f5398d402fcd5997e2

**Comment by roman01la** [comment]
@tonsky I guess this is already solved?

**Comment by tonsky** [comment]
yes, in https://github.com/tonsky/rum/commit/1390fbc83706a423410b4fbf38bf265762e202ca
