### ISSUE TITLE
Error is thrown when using special characters in a string

### ISSUE THREAD

**Issue by groundedsage** [tonsky/rum#135]
I had this issue some time ago and thought it was a Boot issue but it appears to be an issue in Rum. My solution was to just create an SVG but for what I am doing now that would be impractical.

It is found when simply doing something like this.
`(rum/defc comp [] [:span "$"])`

Then calling it. It only seems to appear when it is compiling the Clojurescript for the first time.

Depending on where I try and use the dollar sign I get.
`java.lang.IndexOutOfBoundsException: No group 4`
`java.lang.IndexOutOfBoundsException: No group 1`
`java.lang.IllegalArgumentException: Illegal group reference`

**Comment by tonsky** [comment]
Can’t reproduce. `[:span "$"]` renders just fine. I’m afraid you’ll need to provide a minimal repo that reproduces the issue

**Comment by groundedsage** [comment]
Apologies I have been away from Clojure land for a period of time. I am using Boot and doing SSR so it would have required a little bit of work for me to put together a repo which I didn't have time to quickly whip up. Upon coming back to work which was throwing this error it appears to have cleared itself up.
