### ISSUE TITLE
Rendering `:on` attributes on server

### ISSUE THREAD

**Issue by piranha** [tonsky/rum#139]
We are rendering AMP pages with Rum, and AMP needs `:on` attributes to make something move -
 like switching images. Those attributes are currently skipped during server rendering. 

I have thought of three options:

- skipping only things that start with `:on-` (AMP needs `:on` exactly)
- some dynamic variable which controls if `:on*` attributes are skipped or not
- some weird prefix which gets removed so that `:prefix-on` is rendered as `:on`

I don't like either of them, but I'd really like to make this work. :)

**Comment by DjebbZ** [comment]
Maybe it can be closed with the recent rum 0.11.2 ?

**Comment by tonsky** [comment]
@piranha? In 0.11.2, if on- attrs are strings, they’ll kept during SSR

**Comment by sansolovyov** [comment]
Cool! We are not on latest version yet because it's hard to make react behave nicely if results of server rendering are different than client one - and that happens with a/b tests and time counters. But I hope to fix this stuff soon. :)
