### ISSUE TITLE
let rum support lambda component

### ISSUE THREAD

**Issue by spagreeks** [tonsky/rum#140]
we have `defc`, that not convenient for init closure variable dynamically. suppose we have `fnc(defc lambda version)`, we don't need rum/local any more:
```clojure
 (defn conter-comp [n]
   (let [cnt (atom n)]
     (fnc < rum/reactive
      []
      [:div (rum/react cnt)])))
```

**Comment by tonsky** [comment]
I believe React wasn’t designed to create classes on-the-fly. Correct me if I’m wrong

**Comment by spagreeks** [comment]
But we are clojurians, :-)
IMO, as a rum beginner, need not to know `React Class` concept. it act like function in rum.
