### ISSUE TITLE
SSR: derived-atom shouldn't use add-watch when used in Clojure

### ISSUE THREAD

**Issue by roman01la** [tonsky/rum#141]
I believe there's no point in watchers for derived atoms since server side rendering is done in a single pass. For example `rum/react` is just `deref`. Would you accept a PR to fix this?

**Comment by tonsky** [comment]
Well I wanted derived atoms to be generally useful, not just for Rum/SSR. Are there any issues you’re struggling with?

**Comment by roman01la** [comment]
Nothing super important, just that it was unobvious to encounter this difference between underlying implementation of rum/react and derived-atom in that sense.

Wouldn't it make more sense to have this particular behavior consistent given the context of Rum and SSR and a separate implementation for general usage as a library?

**Comment by roman01la** [comment]
original issue reported in Scrum repo here https://github.com/roman01la/scrum/issues/13#issuecomment-306195327

**Comment by roman01la** [comment]
I don't mind if you prefer to leave this unchanged :)

**Comment by roman01la** [comment]
Closing this
