### ISSUE TITLE
Context and js object

### ISSUE THREAD

**Issue by darkleaf** [tonsky/rum#142]
`child-context` function return cljs map, but [internally deeply converted](https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.cljs#L101)  into js object.
I want to pass cljs data structure into context and retrieve the same data structure.

As workaround I wrap my data with  function. 

```clojure
(def ^:private provider-mixin
  {:child-context
   (fn [state]
     (let [[value & _] (:rum/args state)]
       {ctx-key (constantly value)})) ;; workaround

   :class-properties
   {:childContextTypes {ctx-key js/React.PropTypes.any.isRequired}}})

(rum/defc provider < provider-mixin
  [value child]
  child)
```

I understand that any changes will break current api.
But is it possible to fix it in the next major version?

**Comment by tonsky** [comment]
Why do you have to convert it to function? Wouldn’t `React.PropTypes.any` work with any object, including CLJS ones?

**Comment by darkleaf** [comment]
Full fix code.

```
(def ^:private ctx-key "ctx")

(def ^:private provider-mixin
  {:child-context
   (fn [state]
     (let [[value & _] (:rum/args state)]
       {ctx-key (constantly value)})) ;; hack

   :class-properties
   {:childContextTypes {ctx-key js/React.PropTypes.any.isRequired}}})

(rum/defc provider < provider-mixin
  [value child]
  child)

(def ^:private receiver-mixin
  {:class-properties
   {:contextTypes {ctx-key js/React.PropTypes.any.isRequired}}})

(rum/defcc receiver < receiver-mixin
  [this callback]
  (let [value ((gobj/getValueByKeys this "context" ctx-key))] ;; hack
    (callback value)))
```

No. PropTypese are unimportant.

Scenario without fix.
When I pass cljs map into provider component.
I get js object as receiver component callback argument.
I expect that I get same cljs map.

I assume that it's happen because [here](https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.cljs#L101) used `clj->js`.
`clj->js` deeply convert data include my map.

**Comment by tonsky** [comment]
Ok I see what we need. `contextTypes` were meant as purely interop feature for accessing existing React components. It would be wrong to re-purpose it for CLJS maps.

What I could do is creating similar facility but with simplified and streamlined CLJS-native interface, much like Rum did for the rest of React.

On the other hand, there’re concerns that using context is not a good practice and might lead to overcomplicated components with hidden dependencies, e.g. mess. I’d prefer people to avoid using context when possible.

The only real question is, then: are there situations when using context is a must? If it’s just a convenience it means that by not having it we’ll force people to write better, cleaner and less complicated components.

Thoughts?

**Comment by darkleaf** [comment]
I expect that wrapper library must not reduce underlying library facilities.
React have warning in context feature documentation.
So app developer must decide use context or not. 

I think that using `clj->js` is a mistake. Rum must perform one level transformation instead deep transformation for `:child-context` result.

```clojure
(def ^:private provider-mixin
  {:child-context
   (fn [state]
     (let [[value & _] (:rum/args state)]
       {:some-key value
        :another-key :foo-bar})) 

   :class-properties
   {:childContextTypes {:some-key js/React.PropTypes.any.isRequired
                        :another-key js/React.PropTypes.any.isRequired}}})

;; context will be js object with "some-key" and "another-key" properties
;; values will be not transformed

;; retrive context:
(let [some-value (gobj/getValueByKeys component "context" "some-key")])
```
I suggest to add the new key `:child-context-clj` and keep  `:child-context` for backward compatibility.

I can make a pull-request with this feature.

**Comment by tonsky** [comment]
> I expect that wrapper library must not reduce underlying library facilities.

That was the main premise of Rum: to simplify and streamline React for ClojureScript, essentially removing unnecessary features :)
