### ISSUE TITLE
Server-side doesn't render :style blocks like Sablono does

### ISSUE THREAD

**Issue by robert-stuttaford** [tonsky/rum#144]
Sablono expects `:style` to be a map of keyword CSS property names to CSS property value strings.

Rum's server-side is rendering whatever is passed in `:style` as a string.

By example, with source code using Sablono's syntax:

```clojure
[:div {:style {:clear “both”}}]
``` 

Server-side Rum outputs:

```html
<div style="{:clear "both"}"></div>
```

When I am expecting:

```html
<div style="clear:both;"></div>`
```

**Comment by roman01la** [comment]
@robert-stuttaford This is still an issue, right?

**Comment by roman01la** [comment]
Alright just checked, this is already fixed.
