### ISSUE TITLE
Camel case attributes renders well but breaks isomorphism

### ISSUE THREAD

**Issue by DjebbZ** [tonsky/rum#149]
Hi,

When rendering a component that props written in Camel case, rum renders them well but re-rendering them client-side breaks React's isomorphism with a non-explicit error.

We saw the problem when using [microdata attributes](https://facebook.github.io/react/docs/dom-elements.html#all-supported-html-attributes). Example :

`[:div {:itemScope true} "some text"]` => renders correctly but React.js warning in the console.
`[:div {:item-scope true} "some text"]` => all good.

React warning :
> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div data-reactroot
 (server) <div data-reactroot

Unfortunately the warning is totally non-explicit about where the problem happened. It tooks us some time to figure it out.

It looks like the checksum is calculated using the version of the attribute written in source code (CamelCase here) but the HTML rendered is using the version of the attribute "fixed", so that client-side React.js calculates another checksum.

No idea how it should be fixed.

**Comment by DjebbZ** [comment]
I think I found something : https://github.com/tonsky/rum/blob/0.10.8/src/rum/server_render.clj#L197

The code at this location is :

``` clojure
(defn normalize-attr-key ^String [key]
  (or (normalized-attrs key)
      (name key)))
```

Since `:itemScope` is not in the map `normalized-attrs`, it calls `(name :itemScope)`.

And `(not= (name :itemScope) (name :item-scope))` since `(not= "itemScope" "item-scope")`.

Still don't know how to fix, but I hope this small investigation will be helpful.

**Comment by zlorf** [comment]
Well, it seems like you just need to add `:item-scope` (and possibly also other microdata attributes) into `normalized-attrs` map.

**Comment by roman01la** [comment]
@DjebbZ I'm not sure what's the expected behavior here, could you clarify?

**Comment by tonsky** [comment]
I might add that

- checksums are gone as far as I remember
- at some point I made a decision that all attributes in Rum should be written in kebab-case and the appropriate name should be deduced from it when converting to appropriate format (text HTML attributes or React/DOM js properties)

So the only problem we’ve got here might be that we don’t break on CamelCase attributes

**Comment by roman01la** [comment]
I think I've just fixed a similar issue https://github.com/tonsky/rum/issues/129
To get custom attributes working between ssr and client use string attribute `{"item-scope" "value"}`, this will render correctly on JVM and won't get converted into camel case on the client
