### ISSUE TITLE
Request: render-static-markup in cljs, for service workers. 

### ISSUE THREAD

**Issue by Zaphodious** [tonsky/rum#160]
Having render-static-markup (and render-html) in core.cljs would be beneficial for working with service workers. Given that a service worker can update app data in the background, it would be rather nifty if a page could be preemptively pre-rendered in the worker at update time (rather then just returning the shell and the rendering code at end user load time).

**Comment by tonsky** [comment]
I guess you can use `ReactDOMServer.renderToString` implementation, can’t you?

**Comment by roman01la** [comment]
marking as duplicate of #105 and closing
