### ISSUE TITLE
:wrap-render decorating

### ISSUE THREAD

**Issue by wnr** [tonsky/rum#162]
Hi,

I'm trying to create a mixin with similar functionalities like https://github.com/ctrlplusb/react-sizeme.
I then need to add extra surrounding html to the original render-fn html, by using :wrap-render. I can't seem to find a way to achieve this currently, as my (render-fn) invocation returns React elements which cannot be used in hiccup.

```clojure

(defn my-mixin
  []
  {:wrap-render (fn wrap-render [render-fn]
                  (fn [state]
                    [:div (render-fn state)]))})

(rum/defc view < (my-mixin)
  [_]
  [:p "hello"])
```

Is there something I'm missing?

**Comment by tonsky** [comment]
Render-fn must return vector of new dom and state `state → [dom state']`
I’m afraid it isn’t documented anywhere. Try this:

```clojure
(defn my-mixin
  []
  {:wrap-render (fn [render-fn]
                  (fn [state]
                    (let [[dom' state'] (render-fn state)]
                      [[:div dom'] state'])))})
```

**Comment by wnr** [comment]
Thank you for your quick response. I actually tried that, but then I get this error:

```
core.cljs?rel=1519728470876:188 Uncaught Error: doc-app-view.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

`dom'` is a React Element object I think, and it seems like the [:div] form does not like that.

**Comment by tonsky** [comment]
No, it should be fine. Try `(js/React.createElement "div" dom')`? Or something similar?

**Comment by wnr** [comment]
Yes, thank you. That did the trick. For future reference, there needs to be a props object or nil between as second argument to `createElement`.
