### ISSUE TITLE
rendering components from call to `repeat` throws error

### ISSUE THREAD

**Issue by jameslaneconkling** [tonsky/rum#166]
From the README

```clojure
(require [rum.core :as rum])

(rum/defc repeat-label [n text]
  [:div (repeat n [:.label text])])
```

throws `Objects are not valid as a React child`.

Converting the sequence to a vector (e.g. `(vec (repeat 5 [:.label "text"]))`) solves the problem, but not sure what the issue is, as rum can handle lazy sequences in all other cases I've tried.

Running with:
```clojure
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.238"]
                 [rum "0.11.2"]]
```

If helpful, I can update the README.

**Comment by roman01la** [comment]
@jameslaneconkling I think this is an issue in Sablono, which is Hiccup to React compiler that is being mused by Rum internally. Please open an issue in Sablono's repo https://github.com/r0man/sablono

**Comment by jameslaneconkling** [comment]
👍 thanks for the pointer.

**Comment by saitouena** [comment]
This issue haven't been reported in sablono issues. https://github.com/r0man/sablono/issues?utf8=%E2%9C%93&q=is%3Aissue
I am new to rum and don't know rum's implementation details, so I can't explain it properly in sablono issue.
Anyway, example in README is broken. It is a problem. At least it should be replaced with `vec` wapped version or another example.
@tonsky What do you think about this?

**Comment by tonsky** [comment]
This was broken by CLJS release
Fixed the README for now, opened a sablono issue

**Comment by saitouena** [comment]
Thank you!
