### ISSUE TITLE
Accessing Component Arguments from Mixins

### ISSUE THREAD

**Issue by theronic** [tonsky/rum#168]
I often need to construct dynamic mixins based on the component arguments, but mixins are declared before component argument definitions. E.g.

```
(rum/defcs some-firebase-monitor
  < (subscribe-children-mixin ref ::my-data) ;; ref is not available here :/
  [state ref]
  [:div "data:" (pr-str (rum/react (::my-data state))))

(rum/defc parent-component []
  [:div (some-firebase-monitor (build-ref "/users/123"))]
```

I see I can use `(:rum/args state)`, but this binds my mixin implementation to the shape of my component argument definition.

Is there a cleaner way?

**Comment by tonsky** [comment]
No, just

```
(let [[ref] (:rum/args state)]
  ...
```

And it will be bound to the shape of your arguments anyway, even if there existed another implementation. If you want to work around that, use map with arg keys as the only argument

**Comment by roman01la** [comment]
I'd suggest to go with something like `(comp your-mixin :rum/args)`

**Comment by roman01la** [comment]
Margin as question and closing
