### ISSUE TITLE
Access native component props from mixins

### ISSUE THREAD

**Issue by nohaapav** [tonsky/rum#172]
Hi, i'm playing with new material UI + rum and so far so good but i found one limitation: 
Check this example from material doc: https://material-ui.com/customization/css-in-js/

They are using `withStyles` wrapper which basically generate some css and attach name of css classes into classes props of native component. Unfortunately i found no way to get into props of native component to fetch these values, i can access only props defined in rum component. Is this 
even possible ?

**Comment by nohaapav** [comment]
Update:

Basically only way i found to get classes props of native component is this one via fibers and component key:

```javascript
{:did-mount
                                 (fn [state]
                                   (js/console.log
                                     (let [fiber (gobj/get (:rum/react-component state) "_reactInternalFiber")]
                                       (loop [root fiber]
                                         (let [root-key (gobj/get root "key")]
                                           (if (= "XXDDSD" root-key)
                                             (gobj/getValueByKeys root "lastEffect" "memoizedProps" "classes")
                                             (recur (gobj/get root "lastEffect")))))))
                                   state)}
```

**Comment by tonsky** [comment]
`(:rum/react-component state)` gives you raw React component, from there consult React impl on how to get what you need.
