### ISSUE TITLE
No protocol method ICollection.-conj  defined for type object: [object SVGSVGElement]

### ISSUE THREAD

**Issue by theronic** [tonsky/rum#177]
My static SVG component throws an exception when I change it. When I wrap the `[:svg {} ...]` component in a [:div], it doesn't happen, but then I can't access the SVG DOM node with `rum/dom-node` (or don't know how).
 
![image](https://user-images.githubusercontent.com/1011676/46243965-ab0ee600-c3d9-11e8-9372-df52b04e6d1f.png)

**Comment by tonsky** [comment]
What do you mean “when I change it”?

**Comment by roman01la** [comment]
@theronic The issue lacks context, please provide more information.

**Comment by roman01la** [comment]
not enough context, closing
