### ISSUE TITLE
Multimethods and rum?

### ISSUE THREAD

**Issue by claj** [tonsky/rum#178]
I have identified a pattern in our code base.

One is a multimethod `page-component` that renders pages based on the current url (handler).

The pattern usually becomes something like:

```
(rum/defc login [sys]
    [:div [:h1 "Login"]
            [:p "Login box..."]])

(defmethod page-component :login [sys]
   (login sys))
```

This feels a bit strange. I would like to be able to have the multimethod returning a rum component, is there anything I'm not aware of or don't understand?

**Comment by tonsky** [comment]
It’ll need support on Rum side. I’ll look into it

**Comment by roman01la** [comment]
In Reagent this just works because components are plain functions, unfortunately with macros in Rum this is not easy. I'm not sure if introducing `defmulti` wrapper into the core is the way to go.

**Comment by roman01la** [comment]
closing this, I don't see how we can fix this
