### ISSUE TITLE
Render Rum component inside a pure React component.

### ISSUE THREAD

**Issue by bago2k4** [tonsky/rum#179]
Hi and thanks for the amazing lib.
I was hoping to use a utility component written in pure JS like this https://github.com/jasonslyvia/react-lazyload with my Rum components.

If my component is called `MyComponent` that library would work like this:
```
<LazyLoad>
   <MyComponent props />
</LazyLoad
```

Now with my `rum-component` i tried something like this:
```
(let [lazy-load-element (.createElement js/React LazyLoad (clj->js props))]
   (lazy-load-element my-component))
```

but nothing, i tried getting the React component out of the Rum defcs but nothing:
```
(lazy-load-element (:rum/class (meta #'my-component)))
```
or even
```
(lazy-load-element (:rum/class (meta #'(my-component))))
```

Is it possible to get the React component out of my Rum defcs to pass it to LazyLoad?

Thanks

**Comment by tonsky** [comment]
I guess it should be `(lazy-load-element (my-component))`. Rum components are functions that, upon calling, return React element. This is what you need to pass to lazy-load, I guess. Let me know if it helps

**Comment by bago2k4** [comment]
Thanks for the quick reply @tonsky 

I tried that way but here is what i get:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <stream-item />. Did you accidentally export a JSX literal instead of a component?
```

Right after that i get an error from `LazyLoad.componentDidMount` saying:
```
Uncaught Error: Unable to find node on an unmounted component.
```

**Comment by tonsky** [comment]
What ix lazyLoad expecting then?

**Comment by bago2k4** [comment]
Not sure... i think it doesn't like the Rum wrapper. Her is LazyLoad Readme if you want to take a look https://github.com/jasonslyvia/react-lazyload

**Comment by tonsky** [comment]
Rum produces pure React components and React classes, no “incompatible” wrappers. If you figure out what you need to pass there I might be able to help you

**Comment by bago2k4** [comment]
Ok, thanks for the help

**Comment by bago2k4** [comment]
Got it, it may help someone so i'll write the solution here.
I was passing my component as prop to the LazyLoad component, instead i need to pass it as child:
```
(.createElement js/React
  LazyLoad
  (clj->js lazy-load-props)
  (my-component my-component-props))
```
