### ISSUE TITLE
What is the rum equivalent of reagent.core/after-render?

### ISSUE THREAD

**Issue by claj** [tonsky/rum#180]
We have a scroll handler for our SPA. We want it to scroll smoothly when there is an internal navigation going on on page (like clicking a target link), and a direct navigation when there is a page change.

This has lead us to some quite complicated setup, where we want to wait for the scrolling to take place until after the new page is rendered when changing page (to get the correct height to scroll to,  we have a "normal" top level and stuff).

In reagent, we had this in an event handler like 

```
(defn install-scroll-restorer
  "When the user navigates to an entry present in the history stack we
  pick the saved scroll position from the event, then:
  1. wait for navigation info to change
  2. wait for rendering to be done
  3. Restore the saved scrolled position."
  []
  (events/listen
   js/window EventType/POPSTATE
   (fn [event]
     (let [state (.-state event)]
       (when-let [scroll-top (when state (aget state "scroll-top"))]
         (reset! restoring? true)
         (r/after-render
          (fn [old-nav new-nav]
            (r/after-render
             #(do (reset! restoring? false)
                  (scroll-to scroll-top)))))))
     nil)))
```

which is somewhat complicated but does the job. (We also have a debouced scroll top saver and some other stuff, it works).

Now we would to have this scroll logic to take place after a react render cycle, but it seems like there is no API to smuggle in this kind of callbacks in React from rum, is that correct?

Where should we put this logic in Rum? As a mixin on the top component? Or just put this into React by interop somehow?

Thanks a lot.

**Comment by tonsky** [comment]
I’m not aware what Reagent after-render does, but Rum mixins support `:after-render` callbacks. Basically it’ll be called on `componentDidMount` and on every `componentDidUpdate` after that. Does that works for you?

**Comment by claj** [comment]
Yes, we solved the problem by putting and :after-render that triggered the navigation on each after render on the top component. We also have another "callback" for cases where the navigation is on the same page, ie no re-rendering is done. Thanks!
