### ISSUE TITLE
Value is updated every other time

### ISSUE THREAD

**Issue by zelark** [tonsky/rum#181]
I've run into some strange behavior. I have 2 inputs with a shared value: the first is a number, the second is a range. A problem is here that the first input's value get updated only every other time. Look at the capture below
![every-other-time](https://user-images.githubusercontent.com/2854582/47145900-85d41000-d2d3-11e8-8dd8-04269bbe9c8e.gif)

and here's the code

```clojure
(defonce app-state (atom { :val 21 }))


(rum/defc wow < rum/static [val]
 [
  [:input { :type :number :disabled true :value val }]
  [:br]
  [:input
  { :type :range
    :min 1
    :max 64
    :value val
    :on-change #(swap! app-state assoc :val (int (-> % .-target .-value)))}]])


(rum/defc component < rum/reactive
  []
  (let [{:keys [val]} (rum/react app-state)]
    [:div
     (wow val)]))


(rum/mount (component)
           (. js/document (getElementById "app")))
```

The key point is that we turn the value into an integer while put it to app-state. Without that the code works as expected.

The same code in pure [React](https://codepen.io/anon/pen/KGoqxM?editors=1011) and even Reagent works correctly.

Is it a bug?

**Comment by tonsky** [comment]
I guess it’s solved in `[sablono "0.8.4"]`. https://github.com/r0man/sablono/commit/db845f12151fa009e3f6b5237d35dad1041cdfbd I didn’t update Rum to it because there were some other issues if I remember correctly, like IE stopped working or something.

**Comment by zelark** [comment]
Seems like a cause. Thanks.

**Comment by zelark** [comment]
Checked it just in case. Your guess is right, `[sablono "0.8.4"]` fixes the problem.

**Comment by roman01la** [comment]
Closing.
