### ISSUE TITLE
Support raw react component classes in place of tag name symbols

### ISSUE THREAD

**Issue by augustl** [tonsky/rum#183]
I'm new to Rum, but it seems to me that you can't pass in a raw react component class, i.e. a 3rd party component, to Rum's hiccup syntax.

Normally, I write like this:

    [:div ....]

I expected this to work, but it seems like it doesn't:

    [js/MyReactComponentClass ...]

If that does in fact not work, let me know, and I'll write up a pull request for it!

**Comment by martinklepsch** [comment]
An explanation on how to render basic JS React components would be a good addition to this section of the README: https://github.com/tonsky/rum#interop-with-react

I think what you do is just calling the component as a function `(js/MyReactComponentClass ,,,)` but not 100% sure.

**Comment by augustl** [comment]
I tested both `[:div (js/MyReactComponentClass ...)]` and `[:div [(js/MyReactComponentClass ...)]]`. All variations ended up with something like

> Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

and

> Error: Objects are not valid as a React child (found: object with keys {key, val, __hash, cljs$lang$protocol_mask$partition0$, cljs$lang$protocol_mask$partition1$}). If you meant to render a collection of children, use an array instead.

The only thing I could make work, was `(.createElement js/React js/MyReactComponentClass ...)`.

The problem with that, is that child elements of `MyReactComponentClass` can't use the hiccup syntax.

But it's very possible that I'm just missing something :)

**Comment by tonsky** [comment]
> The only thing I could make work, was (.createElement js/React js/MyReactComponentClass ...).
> The problem with that, is that child elements of MyReactComponentClass can't use the hiccup syntax.
> But it's very possible that I'm just missing something :)

This seems correct. To convert hiccup into React element try calling `sablono.core/html`

**Comment by augustl** [comment]
Nice, that should work, then!

Do you want a PR for `[js/MyComponentClass ...]`? 

Or maybe just a PR that mentions `(.createElement js/React js/MyReactComponentClass #js {} (sablono.core/html ...))` in the README instead?

**Comment by tonsky** [comment]
> Do you want a PR for [js/MyComponentClass ...]?

That would go to Sablono, not here.

> Or maybe just a PR that mentions (.createElement js/React js/MyReactComponentClass #js {} (sablono.core/html ...)) in the README instead?

Not in README, but in https://github.com/tonsky/rum/blob/gh-pages/doc/react-interop.md would be fine, thanks

**Comment by augustl** [comment]
Thanks! Will poke the sablono folks.
