### ISSUE TITLE
Backend-side, multiple returns do not work with rum/with-key

### ISSUE THREAD

**Issue by jacomyal** [tonsky/rum#185]
It appears that, backend-side, it is not possible at the moment to render a component that returns multiple elements inside a `rum/with-key` call.

The most simple way to reproduce it is to open the [multiple_return.cljc](https://github.com/tonsky/rum/blob/28f74210b9b129900e51fd4c248931f664f0a595/examples/rum/examples/multiple_return.cljc) example, and wrap the `child` in `ulist` in a `rum/with-key` call:

```clojure
;; ...
(rum/defc ulist [child]
  [:ul {}
   (rum/with-key child "some-key")])
;; ...
```

Then, while trying to build the examples, the error `Expected a keyword as a tag` appears.

It comes from the fact that, backend-size, the [`rum/with-key`](https://github.com/tonsky/rum/blob/28f74210b9b129900e51fd4c248931f664f0a595/examples/rum/examples/multiple_return.cljc) function always assumes that it gets a vector with a keyword as first element.

In my case, I can use a mixin with a `:key-fn` instead, which works fine (thanks @DjebbZ for the help, BTW).

**Comment by tonsky** [comment]
How do you expect key should be applied to multiple children?

**Comment by jacomyal** [comment]
Good question indeed. But since the keys don't end up in the HTML, I don't see why the fonction does anything at all, actually. Also, the fact that it works in CLJS makes it quite inconsistent.

**Comment by roman01la** [comment]
To clarify, in this case `key` gets assigned onto `multiple-return` component on the client side, not the sequence itself.

**Comment by jacomyal** [comment]
Oh nice, thanks!
