### ISSUE TITLE
Anyone managed to get code-splitting with React working?

### ISSUE THREAD

**Issue by DjebbZ** [tonsky/rum#186]
Hello,

I'm trying to integrate [React.lazy and React.Suspense](https://reactjs.org/docs/code-splitting.html#suspense) from React 16.6.0 with Rum in ClojureScript with code-splitting, and I'm failing hard. Basically I'm trying to do something like (everything is inlined for simplicity):

``` clojure
(rum/defc some-component
          []
          (js/React.createElement js/React.Suspense
                                  #js {:fallback (sablono.core/html [:h3 "PLACEHOLDER"])}
                                  (js/React.createElement (js/React.lazy (fn []
                                                                           (js/Promise. (fn [resolve-p reject-p]
                                                                                          (loader/load :popin
                                                                                                       (fn []
                                                                                                         (let [component (resolve 'yoda.components.popin-content/dummy)]
                                                                                                           (resolve-p (component))))))))))))


```

I've put many `console.log` and it clearly shows that the problem comes from where I resolve the promise `(resolve-p (component))`. All my attempts (which are variations of the code above) resulted in React telling me in the console that 

> "Object is not valid React child" 

or

> "Warning: lazy: Expected the result of a dynamic import() call. Instead received: #'my- 
  app.components/dummy (Note: it's the Var of the component) 
  Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))

or

> "Warning: lazy: Expected the result of a dynamic import() call. Instead received: [object Object] 
  Your code should look like: 
  const MyComponent = lazy(() => import('./MyComponent'))

I've tried so many combinations of functions, `rum/defc`, `(js/React.createElement ...)` that I've lost count. Does someone here managed to get something working? Working solutions very appreciated.

**Comment by DjebbZ** [comment]
I got a little further: now that last expression is `(resolve-p #js {"default" component})`. And I get a new error message:

> react-dom.inc.js:49 Uncaught Invariant Violation: Element type is invalid. Received a promise that resolves to: #'yoda.components.popin-content/dummy. Promise elements must resolve to a class or function.

I think my problem boils down to this: given a Var that I get with `(cljs.core/resolve 'fully.qualified/symbol)`, how can I retrieve the corresponding React Component ? React complains that I don't resolve the promise with a valid React component.

**Comment by tonsky** [comment]
try `(:rum/class (meta ctor))` where ctor is the function stored in component defined with `defc`

**Comment by DjebbZ** [comment]
It almost works. It happens that `(cljs.core/resolve 'namespace/component-symbol)` returns a Var, so you have to deref it to get the underlying constructor: `(:rum/class (meta @component))`.

Thanks a lot!

I suppose it would make a good addition to the interop doc.

**Comment by DjebbZ** [comment]
Sorry to reopen so quickly but now I have another problem. Given a constructor as done above, how does one call it inside rum ? My problem is that for la lazy-loaded component that takes no argument, it works fine. But the lazy loaded component I really want to use takes argument, I can't find a way to pass arguments to the lazy loaded component.

Here's my example:

``` clojure
(let [component (-> (resolve 'my-app.components/dummy)
                    (deref)
                    (meta)
                    (:rum/class)
                    #_(partial arg1 arg2))]
  (resolve-p #js {"default" component}))
```

If I make `dummy` take no argument, works perfectly. I tried making a partial, doesn't work. I also tried after reading the source code passing arguments the "rum" way, like this (full example, real-world code, just inlined):

``` clojure
(rum/defc render-popin-placeholder < rum/static
          [arg1 arg2]
          (js/console.log "popin placeholder")
          (js/React.createElement js/React.Suspense
                                  #js {:fallback (sablono.core/html [:h3 "PLACEHOLDER"])}
                                  (js/React.createElement (js/React.lazy (fn []
                                                                           (js/console.log "INSIDE React.lazy")
                                                                           (js/Promise. (fn [resolve-p reject-p]
                                                                                          (loader/load :popin
                                                                                                       (fn []
                                                                                                         (js/console.log ":popin module loaded")
                                                                                                         (let [component (-> (resolve 'my-app.components/real-popin)
                                                                                                                             (deref)
                                                                                                                             (meta)
                                                                                                                             (:rum/class)
                                                                                                                             #_(partial reconciler popin-state))]
                                                                                                           (js/console.log "popin component" component)
                                                                                                           (resolve-p #js {"default" component}))))))))
                                                          #js {":rum/initial-state" {:rum/args [arg1 arg2]}} ;; nope
                                                          ; #js {":rum/args" [reconciler popin-state]} ;; also tried this
                                                          )))
```

When I console.log the arguments inside `real-popin`, I get `undefined`.

Again, help really appreciated. I realize I'm doing some "edgy" interop between rum and the new features in React.

**Comment by tonsky** [comment]
Something like this:

```
(js/React.createElement class #js { ":rum/initial-state" { :rum/args args }})
```

**Comment by DjebbZ** [comment]
I tried this too, didn't work (not sure I understand why since this is what rum does...)

**Comment by DjebbZ** [comment]
Sorry for the delay, I had already tried this before and it didn't work. I
ended up not using React.lazy and not using code-splitting which is a bit
frustrating. I hope to find a solution in the future and will update this
issue accordingly. Thanks for your time.

I suggest to keep this issue opened since it's still an open question.

**Comment by mahsa2** [comment]
I have managed to get code-splitting working using the **shadow-cljs** library and the code below:

```clojure
(ns util.code-splitting
  (:require [promesa.core :as p]
            [shadow.lazy :as lazy]
            ["react" :as react]))

(defmacro lazy-component [loadable-comp & args]
  `(lazy-component* (lazy/loadable ~loadable-comp) ~@args))

(defn lazy-component* [loadable & args]
  (react/createElement react/Suspense
    #js {:fallback (sablono.core/html [:h3 "PLACEHOLDER"])}
    (react/createElement
      (react/lazy
        #(-> (lazy/load loadable)
             (p/then (fn [_] #js {:default (-> loadable deref meta (:rum/class))}))))
      #js {":rum/initial-state" {:rum/args args}})))
```
and, use it:
```clojure
(ns ... 
  (:require-macros [util.code-splitting :refer [lazy-component]]))
(lazy-component my-app.components/real-popin arg1 arg2)
```
Hope it helps.

**Comment by roman01la** [comment]
Closing and marking as question.

**Comment by DjebbZ** [comment]
Sorry to bother you, for me it's still an open problem. We don't use `shadow-cljs` and have no plan to use it anytime soon. I think a solution should still be possible, right?

**Comment by roman01la** [comment]
@DjebbZ Sure, no problem. For me it doesn't seem like there's an issue in Rum, but rather a lack of a guide on how to implement lazy loading. Could you please describe your problem in details?

**Comment by DjebbZ** [comment]
It's been a long time and I thought my reports above went into enough details, but basically when lazy-loading a React component with ClojureScript's code-splitting I didn't find a way get a hold on the React component itself that React suspense expects, only on some kind of CLJS Var object that React didn't like.

**Comment by DjebbZ** [comment]
Maybe you get the idea since you implemented explicit support for it with UIx (if I'm not mistaken). The results of loading a CLJS code-split module isn't compatible as-is with React, and all my attempts to "convert" or "get inside" it failed. See my reports above for the various ways I tested. I think the problem is "mostly" syntactical, or there's some (un)wrapping to (un)do.

**Comment by roman01la** [comment]
@DjebbZ Here's example implementation https://github.com/roman01la/rum-code-splitting

I'll file a ticket to not forget to get this into Rum once I resume work on new API wrappers

**Comment by DjebbZ** [comment]
Oh you just created an example repo just for me, thanks! I'll wait for the official API since I'm not in a hurry.

**Comment by roman01la** [comment]
Good, the let's close this. I've created an issue for Suspense API.
