### ISSUE TITLE
Render empty attributes?

### ISSUE THREAD

**Issue by bfontaine** [tonsky/rum#187]
:wave: Hi,

I wanted to render a value-less attribute like [`itemscope`](https://developer.mozilla.org/fr/docs/Web/HTML/Attributs_universels/itemscope), but looking at the code it doesn’t appear to be possible.

```html
<div itemscope itemtype="...">...</div>
<!-- ^^^^^^^^^ -->
```

Would you be ok if I make a PR adding a special value like `:rum/empty` that Rum would interpret as "render this attribute without any value"?

**Comment by claj** [comment]
It's a good idea. But it usually works just fine to set it to something, like

`[:div {:itemscope true} ...]`

It seems like the check is for the existence of the attribute rather than its exact value. Or have you find a case where the "naked key" is nescessary?

**Comment by bfontaine** [comment]
That’s true, after checking `itemscope=""` is as valid as `itemscope`. Thanks for the comment!
