### ISSUE TITLE
Addition to 'Who's using Rum'

### ISSUE THREAD

**Issue by gmp26** [tonsky/rum#189]
Last week we launched the Rum app https://prostate.predict.nhs.uk -  'An individualised prognostic model for men newly diagnosed with non-metastatic prostate cancer'. 
This complements the previous breast cancer Predict tool, which is now moving to https://breast.predict.nhs.uk.

Would it be possible to add Prostate Predict and update the previous 'Predict' entry to 'Breast Predict' and update its URL? 

The press release for the Prostate tool is here: 
https://www.cam.ac.uk/research/news/evidence-based-web-tool-aims-to-better-inform-and-refine-need-for-treatment-in-early-prostate-cancer

**Comment by tonsky** [comment]
Sure, done!
