### ISSUE TITLE
`rum/render-html` on a component with a vector of elements is broken

### ISSUE THREAD

**Issue by livtanong** [tonsky/rum#195]
Broken
```clj
(rum/defc Derp < rum/static [] [:div [[:div] [:span]]])
;; Expected a keyword as a tag
```

Works if it's a list
```clj
(rum/defc Derp < rum/static [] [:div '([:div] [:span])])
;; "<div data-reactroot=\"\"><div></div><span></span></div>"
```

**Comment by tonsky** [comment]
That’s how it’s supposed to work. Vectors are reserved for tags, lists for grouping elements.

**Comment by green-coder** [comment]
@tonsky I think that there is this piece of code in `README.md` which is confusing the users:

```clojure
(rum/defc repeat-label [n text]
  [:div (vec (repeat n [:.label text]))])
```

You use `vec` there.

**Comment by tonsky** [comment]
Thanks! I suppose that was a mistake

**Comment by livtanong** [comment]
Ah, you're right, the hiccup syntax says sequences are for collections of elements. However, when i use a vector of elements in clojurescript, it works as if I had used a sequence. Seems to me this inconsistency could be a source of confusion for other people and not just for me. That being said, would this be an issue with Sablono?

**Comment by tonsky** [comment]
> That being said, would this be an issue with Sablono?

Yes
