### ISSUE TITLE
Render server-side HTML from ClojureScript

### ISSUE THREAD

**Issue by theronic** [tonsky/rum#210]
Hi Tonsky, is it possible to render an HTML string from Rum in ClojureScript if no React connectivity is required? I see there is rum/render-html, but it seems to depend on StringBuilder and JVM.

I'm using Rum on a Cljs project that has a NodeJs component and would like to be able to share my view code between the frontend and the backend.

**Comment by tonsky** [comment]
I think it shouldn’t be that hard to introduce reader conditional and swap out StringBuilder to just string concatenation in JS. The current Rum maintainer is @roman01la though, I’ll let him make the call

**Comment by roman01la** [comment]
Yeah we can do that, could be a nice feature, I'll put  a pr later

**Comment by roman01la** [comment]
One note however, for jvm rendering we have a dummy API for mixins/hooks defined in clj, while cljs code depends on react. I'm not sure it's a good idea to add checks or a flag to switch from react to own impl, we'd have to account a fallback for every public API with runtime checks.

**Comment by roman01la** [comment]
Not working on this. When in cljs Rum components return React components, not plain Hiccup.
