### ISSUE TITLE
textarea's not updating from a rum/react

### ISSUE THREAD

**Issue by CmdrDats** [tonsky/rum#225]
Using `rum "0.12.3"`

I'm having an issue with textarea's not updating when an atom changes - I had an issue on 0.11.5, where inputs would skip every second update (?!) but that seems to have been fixed in the latest release, thankfully.

```clojure
(def price-atom (atom 123))
(rum/defc edit < rum/reactive []
  [:div
   [:button
    {:on-click (fn [] (reset! price-atom 10))}
    "Price 10"]

   [:button
    {:on-click (fn [] (reset! price-atom 768))}
    "Price 768"]
   [:button
    {:on-click (fn [] (reset! price-atom 1024))}
    "Price 1024"]

   [:b (pr-str (rum/react price-atom))]
   (pr-str [:textarea (rum/react price-atom)])
   [:textarea (rum/react price-atom)]
   [:input {:value (rum/react price-atom)}]])


(rum/defc root []
  [:div (edit)])

(defn start []
  (rum/mount
    (root)
    (.getElementById js/document "mnt")))
```
The html here is bare bones with a `<div id="mnt"></div>` in the body tag.

Is there something special about textarea's that I don't know about?

![Showcase textarea issue](https://user-images.githubusercontent.com/1006584/87677166-bb907c00-c779-11ea-8714-867878972c6c.gif)

Thanks a mil!

**Comment by roman01la** [comment]
textarea's value should be set via `:value` attribute
```clojure
[:textarea {:value value}]
```

**Comment by CmdrDats** [comment]
aha - great, thanks! that works. strange.. I remember testing textarea's a while back and they _couldn't_ be in the `:value` attribute.. oh well, maybe I did something else wrong at the time.

Apologies for logging a user-side issue!
