### ISSUE TITLE
Perceived performance regression between Rum 0.11.5 and 0.12.3

### ISSUE THREAD

**Issue by CmdrDats** [tonsky/rum#226]
To properly illustrate, I've created: https://github.com/CmdrDats/rumperftest - screenshots and instructions to replicate are there.

In short, it looks like the rendering is now synchronous on input changes, so it makes existing apps feel much slower.

**Comment by roman01la** [comment]
We won't roll back to async rendering, the goal for now is to keep impl simple and stick to what React provides. This also finally resolved issues with inputs
