### ISSUE TITLE
rum/fragment with React components 

### ISSUE THREAD

**Issue by martinklepsch** [tonsky/rum#227]
``` clj
  (rum/fragment
    (EventDescription event)
    (EventGameList r event opts)
    (EventRoomActions event opts))
```

Using `rum/fragment` with components like above results in the following error: 

```
Invalid prop `#object[f]` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
``` 

Is this expected and `rum/fragment` only supports hiccup as described in the README or should this work?

Thanks!

EDIT [React Fragment docs](https://reactjs.org/docs/fragments.html) seem to indicate this should work with components.

**Comment by roman01la** [comment]
yeah I think atm props map/nil is required, I'll change this, thanks!

**Comment by roman01la** [comment]
@martinklepsch fyi Rum supports Reagent's `:<>` syntax for Fragments
