### ISSUE TITLE
What is the idiomatic way of managing state?

### ISSUE THREAD

**Issue by jkhoeini** [tonsky/rum#24]
In reagent you can return the render function instead of directly returning the component description.[1](https://github.com/Day8/re-frame/wiki/Creating-Reagent-Components#form-2--a-function-returning-a-function)
So you can do this, for example:

``` clojure
(defn timer-component []
  (let [seconds-elapsed (reagent/atom 0)]     ;; setup, and local state
    (fn []        ;; inner, render function is returned
      (js/setTimeout #(swap! seconds-elapsed inc) 1000)
      [:div "Seconds Elapsed: " @seconds-elapsed])))
```

I'm wondering what is the corresponding solution in rum.

**Comment by tonsky** [comment]
`rum/defc` defines a regular function, you can wrap it with another function or choose any other way to closure over timer reference. One solution:

``` clj
(rum/defc timer-comp < rum/reactive [seconds-elapsed]
  (js/setTimeout #(swap! seconds-elapsed inc) 1000)
  [:div "Seconds elapsed: " (rum/react seconds-elapsed)])

(defn timer []
  (let [seconds-elapsed (atom 0)]
    (timer-comp seconds-elapsed)))

(rum/mount (timer) js/document.body)
```

`rum/reactive` is needed so `timer-comp` will self-update when `seconds-elapsed` changed.

`js/setTimeout` is called in a render function. This is ok if you can gurantee nobody else (e.g. parent) will re-render your component. But if render (for whatever reason) will be called twice, you’ll get 2 timers ticking, and so on. This flaw is also in your original reagent example. Generally I do not advise to do that. Render should be always side-effect free.

It might be better to offload component state to somewhere, and create state-less component. This way you can re-render `timer-comp` as much as you want, it’ll always show the current time, because state is decoupled from component.

``` clj
(js/setInterval #(swap! seconds-elapsed inc) 1000)

(rum/defc timer-comp < rum/reactive []
  [:div "Seconds elapsed: " (rum/react seconds-elapsed)])
```

Rum works best when state is managed not by each component, but by some external, global, well-defined process.

Third possibility is to create a mixin. This way you can create true, safe, per-component state nobody else will see or be able to tamper with. Rum is not optimized for such use-cases, so it’s a bit longer:

``` clj
(def timer-mixin {
  :did-mount (fn [state]
               (let [ref      (atom 0)
                     interval (js/setInterval #(do
                                                 (swap! ref inc)
                                                 (rum/request-render (:rum/react-component state)))
                                              1000)]
                 (assoc state ::interval interval
                              ::ref ref)))
  :transfer-state (fn [old-state state]
                    (merge state (select-keys old-state [::ref ::interval])))
  :will-unmount (fn [state]
                  (js/clearInterval (::interval state)))
  })

(rum/defcs timer-comp [state]
  [:div "Seconds elapsed: " @(::ref state)])

(rum/mount (timer-comp) js/document.body)
```

Note that I used `defcs`, it’s a macro that delivers state map to render function as first argument (you do not pass it explicitly when calling `(timer-comp)`, of course).

Or, if you want to repeat Reagent example and set timeout in render function, this:

``` clj
(def timer-mixin {
  :did-mount (fn [state]
               (let [ref  (atom 0)
                     comp (:rum/react-component state)]
                 (add-watch ::render ref (fn [_ _ _ _] (rum/request-render comp)))
                 (assoc state ::ref ref)))
  :transfer-state (fn [old-state state]
                    (merge state (select-keys old-state [::ref])))
  })

(rum/defcs timer-comp [state]
  (js/setTimeout #(swap! (::ref state) inc) 1000)
  [:div "Seconds elapsed: " @(::ref state)])

(rum/mount (timer-comp) js/document.body)
```

**Comment by jkhoeini** [comment]
Yeah, Thanks a lot for your thorough answer.

I have a code base which was originally written using Om. Then I switched it to Reagent, since I didn't appreciated the idea of all my state (including presentational ones) accumulated in an atom.
Also, the API was so verbose and OO style.

Now, I'm considering switching to rum, and probably use Datascript for my state. Yet, still I don't like my local and presentational state to end up beside other data. I have a lot of this kind of state. For example, form inputs. Or view states, like tabs. And some animations. It appears to me that the need for presenting and managing this kind of state is very real. And it needs to be managed inside the very component that it belongs to. So, maybe some facility to help with that might be a common need for rum's users.

What I imagine is in line with your answer. In your first approach, where you enclosed the component constructor over another function, I think that this approach is probably enough for most use cases. I saw that you used this very approach in the example.cljs in the repo. But the var that `defc` macro introduces I think is in the way. If there was another macro, perhaps something like `fc` :o) which didn't introduce a global binding, the code could simplify to:

``` Clojure


(defn timer []
  (let [seconds-elapsed (atom 0)
        comp (rum/fc < rum/reactive []
               [:div "Seconds elapsed: " (rum/react seconds-elapsed)])]
  (js/setTimeout #(swap! seconds-elapsed inc) 1000)
  (comp)))

(rum/mount (timer) js/document.body)
```

Much more elegant, I would say.

The second approach, I already explained why I don't like.

About the third approach, I think is the most solid one. However, as you mentioned it it's not that strait forward. I think there are some solutions that can be taken to make it easier to use this approach. First is to introduce a mixin generator for it. So, we can do something like this:

``` clojure
(rum/defcs timer < (state-mixin {:timer (atom 0)}) rum/reactive [state]
  (js/setTimeout #(swap! (get-in state [:rum/state-ref :timer]) inc) 1000)
  [:div "Seconds elapsed: " (rum/react (get-in state [:rum/state-ref :timer]))]
```

And maybe several other helper functions to further ease it out.

And another approach can be to introduce a new syntax:

``` clojure
(rum/defc! timer
  "A timer component"
  < some mixins
  ! [timer 0]    ; A let style set of bindings
  []             ; Params
  (js/setTimeout #(swap! timer inc) 1000) ; timer by defaut has atom semantics; and updating it schedules component for update
  [:div "Seconds elapsed: " @timer])
```

I'm aware of the problem of `setTimeout` in render function. However, I borrowed this example from the link I provided in the first post. And it serves only as an example. :smiley: 

Thanks a lot for the answer.

**Comment by rauhs** [comment]
I think non-`def` versions would be a nice to have.

A quick hack that gets you there:

```
(defn -c [render-ctor body]
  ;; the last removes the def and just gets the let
  (last (#'rum/-defc render-ctor (cons 'dummy body))))

(defmacro c [& body]
  (-c 'rum.core/render->mixin body))

(defmacro cs [& body]
  (-c 'rum.core/render-state->mixin body))

(defmacro cc [& body]
  (-c 'rum.core/render-comp->mixin body))
```

Now allows to do a 

```
(defn timer []
  (let [seconds-elapsed (atom 0)
        comp (rrum/c < rum/reactive []
                       (js/setTimeout #(swap! seconds-elapsed inc) 1000)
                       [:div "Seconds elapsed: " (rum/react seconds-elapsed)])]
    (comp)))
```
