### ISSUE TITLE
Server/client difference when rendering nil

### ISSUE THREAD

**Issue by simongray** [tonsky/rum#246]
In the server portion of Rum `nil` seems to be converted to a string when it's an attribute value, while in the client code `nil` is ok to have as an attribute value. I suppose that it is due to [this line](https://github.com/tonsky/rum/blob/gh-pages/src/rum/server_render.clj#L42) in `rum.server-render`.

Thus, if you have Hiccup similar to this in a hydrated component

```clojure
[:a {:class (get m k)}]
```

for a nonexistent `k` in `m`, I get this React warning when hydrating (details omitted):

```
module$node_modules$react_dom$cjs$react_dom_development.js:2 Warning: Prop `className` did not match. Server: "null" Client: ""
at a
at class$ ...
```

**Comment by tonsky** [comment]
Do you want to provide a PR? Should be an easy fix, and I’m happy to merge it

**Comment by simongray** [comment]
Hm, I can't seem to recreate the issue now, so it was possibly due some quirk in my local setup. I will close for now and reopen in case I run into the same issue. Sorry about that!
