### ISSUE TITLE
Consider moving to 'virtual-dom' project

### ISSUE THREAD

**Issue by kirillsalykin** [tonsky/rum#25]
Please look https://github.com/Matt-Esch/virtual-dom.

I guess this has similar to rum philosophy regarding state management.

**Comment by peeb** [comment]
+1

**Comment by neverfox** [comment]
I guess I don't understand. Vdom is an alternative React for DOM rendering and this is a React library. While you could implement a similar abstraction over Vdom, it seems like that should be its own project.

**Comment by tonsky** [comment]
Yes, I guess I can’t hide the fact it’s based on react and people use it in conjunction with React components. I should’ve closed that earlier
