### ISSUE TITLE
How can I use npm based react library I rum ssr mode

### ISSUE THREAD

**Issue by idhowardgj94** [tonsky/rum#258]
As title, I would like to try to implement a full stack web application use rum, 

but now I have a question, if I want to use the ssr feature, how do I define my view if this view contain npm base 3 party library?

**Comment by tonsky** [comment]
Like, from node.js? Our SSR is Clojure-based, there’s no SSR in js library

**Comment by idhowardgj94** [comment]
Yes, like to use 3 party hi kit library like mui, so there is no chance to use npm base ui kit in ssr render?

**Comment by tonsky** [comment]
I never tried. But technically it’s still React, so maybe React solutions will apply?

**Comment by idhowardgj94** [comment]
I get thx, I'll try it.
Close this issue now because its not a bug
