### ISSUE TITLE
DataScript integration?

### ISSUE THREAD

**Issue by stephanos** [tonsky/rum#3]
rum seems very interesting! I'd love to have components that get data from DataScript and automatically re-render on change. Do you think that is easy to do with rum?

**Comment by tonsky** [comment]
@stephanos I have this application which I just ported to Rum: https://github.com/tonsky/datascript-menu

It may not be beautiful, but you can get the idea. There’s code at the bottom that triggers top-down re-rendering on any DB change (commented), and there’s code that subscribes to specific transaction patterns (listen-for).

Later is more efficient, but is not in DataScript yet. Eventually end up here, for now, as you can see, it can be implemented without deep integration with DS internals, in user code.

**Comment by stephanos** [comment]
Thanks, I'll look into it :)
