### ISSUE TITLE
Patterns for efficient rendering of components that take callbacks

### ISSUE THREAD

**Issue by lynaghk** [tonsky/rum#34]
I'm using Rum to build reusable components.
These components typically don't have local state --- they're "controlled components" that take a `value` and `on-change` callback as arguments:

``` clojure
(rum/defc *color-picker < rum/static
  [color on-change]
  [:input {:type "color" :value color :on-change #(on-change (.-value (.-target %)))}])
```

Their parents use this callback to propagate new values across the app:

``` clojure
(rum/defc *parent < rum/static
  [parent-id color]
  [:div
   [:h1 {:style {:background-color color}} parent-id]
   (*color-picker color #(update-color-elsewhere-in-app! parent-id %))])
```

Semantically everything works great, but I'm having trouble with performance.
Using `rum/static` doesn't help because the `on-change` callbacks are anonymous functions --- on each render of the parent's body, a new `on-change` is created that is not equal to the previous `on-change` callback.

Are there any recommended patterns for handling this situation?
The only solution I can think of is to pass the functions in as vars rather than closures.
E.g., the above example would become:

``` clojure

(rum/defc *color-picker < rum/static
  [color on-change-args]
  [:input {:type "color" :value color :on-change #(apply (first on-change-args) (rest on-change-args) (.-value (.-target %))}])

(rum/defc *parent < rum/static
  [parent-id color]
  [:div
   [:h1 {:style {:background-color color}} parent-id]
   (*color-picker color [update-color-elsewhere-in-app! parent-id]))])
```

but this doesn't strike me as a great solution.

**Comment by tonsky** [comment]
a custom mixin maybe? The one that will only compare arguments you need?
Take a look at rum/static, it’s code is trivial

**Comment by lynaghk** [comment]
I'm hoping to come up with a general solution for the problem of callbacks --- ignoring them won't always yield correct behavior.
E.g., if the color-picker is part of a "background color for selected object" palette that is always mounted and the `on-change` callback passed to it varies depending on the currently selected object, than we _do_ want to re-render the picker when a new object is selected and a new `on-change` callback is given to the color picker.

Another way of framing the problem is thinking about partial application --- I want:

``` clojure
(= (partial f 1 2 3)
   (partial f 1 2 3))

(not= (partial f 1 2 3)
      (partial f 2 3 4))
```

**Comment by lynaghk** [comment]
The best I've been able to do is implement the closure manually using `defrecord`.
In my application I pass DataScript transaction data to a global `trigger!` function, so the callback record looks like:

``` clojure
(defrecord CallbackTxAdd
  [trigger! id attr]
  IFn
  (-invoke [_ val]
    (trigger! :transact {:tx-data [[:db/add id attr val]]})))
```

This record can be passed in like this:

``` clojure
(*color-picker color (CallbackTxAdd. trigger! parent-id :style/color))
```

and pure rendering works as I'd like, because of record equality:

``` clojure
(= (CallbackTxAdd. trigger! parent-id :style/color)
   (CallbackTxAdd. trigger! parent-id :style/color))
;;=> true
```

Leaving this issue open in case anyone wants to propose alternatives.
(@tonsky feel free to close, of course, if you'd rather this sort of discussion happen outside of the issue tracker.)

**Comment by roman01la** [comment]
@lynaghk These days callback caching can be handled using `React.useCallback` hook. The only thing missing is `rum.core/static` for functional components, see https://github.com/tonsky/rum/issues/202

I'm gonna close this issue.
