### ISSUE TITLE
Order of arguments to defc

### ISSUE THREAD

**Issue by luxbock** [tonsky/rum#4]
`defc` is different from almost all of the other `def-something` forms seen in the Clojure world in that its first argument is not the name of the thing being defined. Would you consider changing the semantics of it to be `(defc name mixin(s) args & body)` instead? I'm guessing your intention was to avoid having two vectors following each other, which might look confusing to a lot of people, but the way it works right now breaks syntax highlighting with most editors.

This is obviously a totally breaking change for a rather petty reason, but I figured that since the project is still so young this might not be such a big deal.

**Comment by tonsky** [comment]
Yes, I’m feeling the same about it. I want to wait a little, gather other issues with syntax, macro etc, and when I have more data, maybe a better solution will emerge

**Comment by sansolovyov** [comment]
What do you think about specifying mixins as metadata? Like `(defc name ^{:mixins []} args & body)`? In that case it makes it very clear what is this list of things, so that there is no confusion. On the other hand, mixins are not metadata really...

**Comment by tonsky** [comment]
I’m thinking something like this:

```
(rum/defc watcher < debug rum/reactive [s]
  [:div (str s ": " (rum/react a))])
```

Both `debug` and `rum/reactive` are mixins. Have no idea how many syntax highlighters it will break. LightTable doesn’t mind
