### ISSUE TITLE
Using build-class

### ISSUE THREAD

**Issue by mhuebert** [tonsky/rum#40]
Following the 'how it all fits together' section in the docs, I'm trying to create and mount a simple React element without using `defc`.

I've created a fresh project with the following code: 

``` clj
(def a
    (rum/build-class
        {:render
         (fn [state]
             [(sablono.core/html [:div "a"]) state])}
        "a-component"))

(rum/mount (rum/element a {} nil) (.-body js/document))
```

Should this work? it gives me a `Uncaught TypeError: Cannot read property 'call' of null` ...

stacktrace:

```
rum.build_class.React.createClass.render    @   rum.cljs?rel=1441294910065:96
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @   react.inc.js:6975
ReactCompositeComponentMixin._renderValidatedComponent  @   react.inc.js:7002
ReactPerf.measure.wrapper   @   react.inc.js:13427
ReactCompositeComponentMixin.mountComponent @   react.inc.js:6423
ReactPerf.measure.wrapper   @   react.inc.js:13427
```

relevant code point: 

```
      :render
      (fn []
        (this-as this
          (let [state (state this)
                [dom next-state] (wrapped-render @state)] ; <<<<<
            (vreset! state next-state)
            dom)))
```

I realize that part of the docs is already incorrect because `build-class` requires two arguments, and the `label-mixin` has a nested map. I'd submit a pull request about those issues but I'd like to get an example working first.

**Comment by mhuebert** [comment]
I should note, what I am ultimately trying to do is use `rum` with `react-router`, which expects React **classes**. I'm not sure if there is any way to use this with `rum` components that have been defined with `defc`, as `defc` returns a function which returns an element. So I was trying to build components using `build-class` when I ran into these errors.

**Comment by tonsky** [comment]
The problem was in README — `build-class` expects vector of mixins, not a single one. My bad. Fixed in README, added assert to `build-class` (https://github.com/tonsky/rum/commit/e1e68aeff6b6245d29e46d1ff7130b7e4dc1c9f5)

As of getting class from `defc`, it is possible: class is stored in metadata of construction fn:

``` clj
(rum/defc my-comp [x]
  [:div x])

(let [class (:rum/class (meta my-comp))]
  (rum/mount (rum/element class {:rum/args ["b"]} nil) js/document.body))
```

**Comment by mhuebert** [comment]
Perfect, thank you!
