### ISSUE TITLE
[question] Redundant wrapping (React) components in self-referencing (Rum) components 

### ISSUE THREAD

**Issue by gsnewmark** [tonsky/rum#49]
In case multi-arity component's fns just call each other with additional arguments, each arity of such self-referencing component still creates its own React component. For instance, this is React's components hierarchy for the [`tree` example component](https://github.com/tonsky/rum/blob/5ad105ce5beb3f65e1ce81004e6d10c43abbeff1/examples/rum/examples.cljs#L335) (notice two `tree`'s, outer one created by [`(tree [:a [:b [:c :d [:e] :g]]])`](https://github.com/tonsky/rum/blob/5ad105ce5beb3f65e1ce81004e6d10c43abbeff1/examples/rum/examples.cljs#L343), and inner one - by [`(tree [:a [:b [:c :d [:e] :g]]] 0)`](https://github.com/tonsky/rum/blob/5ad105ce5beb3f65e1ce81004e6d10c43abbeff1/examples/rum/examples.cljs#L336)): 

![tree component hierarchy](http://i.imgur.com/vPCodUb.png)

Such behaviour is quite logical when each arity produces slightly different components (or completely different ones), but when they simply call next arity with additional default arguments (like `tree` example) wrapping components seem redundant, and can cause some problems (for example, if custom `did-mount` is used, it would be called for each wrapping component).

So, is there any chance that in future `Rum` would support addition of mixins to the specific arities of multi-arity component and/or would remove redundant wrappers from produced component hierarchy of multi-arity component?

**Comment by tonsky** [comment]
Do you think this is important enough to fix? Why?

**Comment by gsnewmark** [comment]
It's not that important, because there are ways to avoid creation of few-level same component hierarchies, e. g. using multi-arity _functions_ which call the single-arity component. Moreover, after additional thinking about it I feel that complexity introduced by possible 'fix' outweighs some minor inconveniences of multi-arity components I described in the issue.

For me the biggest problem was that initially I didn't really understand nature of multi-arity Rum components (each render fn of such components produces independent instance of React component) and because of this used them incorrectly (I was adding global event handler in multi-arity component's `did-mount` and this handler was fired a couple of times on each event - it took some time to find the real reason of such behavior).

**Comment by tonsky** [comment]
I gave it a look, it can be solved by giving anonymous render fn a name, but when used, it looked really bad and confusing. Better use a standalone multi-arity render function that is called from component.
