### ISSUE TITLE
Render on atom change outside of event handler, like Reagent

### ISSUE THREAD

**Issue by robinchew** [tonsky/rum#51]
Hello,

In the Readme file, it says:

> On higher level, Rum comes with already-built types of components which emulate behavior found in Om, Reagent and Quiescent"

It makes me think that Rum can already work exactly like Reagent, but I think that is not the case because one feature that Reagent can do that Rum cannot do out of the box is the following, as referenced from https://reagent-project.github.io/news/reagent-is-async.html:

> ... proper batching of renderings even when changes to atoms are done outside of event handlers (which is great for e.g core.async users).

So is there a plan to match at least that feature of Reagent?

Example piece of code below shows an input that can only accept numbers. Typing in alphabet keys will not render the alphabets at all in the input in Reagent, but does render for a split second with the Rum code below.

``` clojure
(def text (atom ""))
(def my-chan (chan))

(rum/defc num-input < rum/reactive []
  [:input {:value (rum/react text) :on-change
    (fn [e] (put! my-chan (string/replace (.-value (.-target e)) #"[a-zA-Z]*" "")))}])

(go
  (while true
    (reset! text (string/replace (<! my-chan) #"[a-zA-Z]*" ""))))

(rum/mount (num-input) js/document.body)
```

@aJchemist has already suggested a solution by using (rum/request-render component) but must be inside the event handler. However does that match the behaviour of Reagent?

Kind regards,
Robin

**Comment by tonsky** [comment]
To understand the behaviour you’ll need to understand all the layers involved.

I’ll start with the facts: if you want good UX with input box, you have to change its value inside `on-change` listener. That’s how browsers work, you can’t change that. If you change input box value outside of listener, if you have any asynchronous behaviour (go block, batching, setTimeout 0, anything), your UX will sucks: flicker, lost cursor position, etc.

React, as you probably know, [messes with input boxes](https://facebook.github.io/react/docs/forms.html#controlled-components). But if you have React’s `on-change` callback that triggers re-rendering of the input box (or its parents) immediately inside `on-change` callback it works just fine. No flickering.

Now why Reagent example works with go blocks. It probably doesn’t retain cursor position (does it? try to type in the middle of the text in the box), but has no flickering: you type a letter, nothing re-renders, some time later go block fires, input box content gets replaced. It might lag (if go blocks are busy, for example), but there’s no place for flicker. You just change A→B, single change, maybe delayed, but it’s atomic.

And then we have Rum. This is where things get ugly. Rum has batched rendering, meaning, `rum/request-render` does not trigger React rendering immediately, instead, it waits for `requestAnimationFrame` to occur, and triggers all batched changes then. If you understand what I was talking about above, you’ll see that would not work for input boxes: even for simplest cases (`[:input {:value (rum/react *value), :on-change (fn [e] (reset! *value (.. e -target -value)))}]`) the re-rendering will be scheduled for some time later, meaning React will have to show not changed text field immediately after key press and change input box value later when animationFrame occurs. It flickers, it messes cursor position, it doesn’t work.

This is why David Nolen invented, and r0man [copied this](https://github.com/r0man/sablono/blob/master/src/sablono/interpreter.cljc#L10-L45). This is a hack to work around that problem with async render: it lets you type anything to input box and it’ll show it immediately, and async render can change this value later. This works ok for normal text input, but is bad for any type of validation: you can see text flicker. Even worse, these hacked inputs are the only type of inputs you can have in sablono, and Rum uses sablono as its DSL for React elements.

One way to fight this is to force _non-async_ re-render in an `on-change` callback of such an input. Another way is to use native React input (via `(js/React.createElement "input")` for example). See how I did it [here](https://github.com/tonsky/rum/blob/gh-pages/examples/rum/examples.cljs#L274-L306).

This is way more complicated than it should be, of course. But it’s what you get if you build standing on the shoulders of the giants.

Let me highlight:
- Rum does allow `request-render` from anywhere
- Reagent’s way of batching changes isn’t magic: you’ll lose your cursor position and see occasional lags
- Things are complicated when you need validation in input box: browser, React and your frontend framework (Reagent, Om, Rum) each adds their own complications
- The only perfect validation can be implemented with native `onChange` callback and `preventDefault`, avoiding React and later layers

**Comment by robinchew** [comment]
Thank you Nikita, I appreciate your comprehensive response. Is my understanding correct that, all React Framework will experience delay between keydown and the next animation frame. The only difference is that Reagent somehow prevents the text from showing in the input after keydown and before animation frame, while OM and Rum just does nothing between keydown and animation frame and just let the text appear. But ultimately all experiences the same delay.

**Comment by roman01la** [comment]
@robinchew Please try to repro this in 0.12.0-SNAPSHOT and report any issues to #205

**Comment by roman01la** [comment]
0.12.0 has been released
