### ISSUE TITLE
Support single-page app with unmount function

### ISSUE THREAD

**Issue by emnh** [tonsky/rum#61]
Add the following function:

``` clojure
(defn unmount [node]
  (js/ReactDOM.unmountComponentAtNode node))
```

See https://facebook.github.io/react/blog/2015/10/01/react-render-and-top-level-api.html.

**Comment by tonsky** [comment]
Thx! Check out v. 0.8.2

**Comment by emnh** [comment]
Works like a charm! Thank you for the quick response!
