### ISSUE TITLE
How to create materialised views from a single state atom (à la Reagent's track)?

### ISSUE THREAD

**Issue by Kauko** [tonsky/rum#75]
Let's say I have the following state:

```
(def model 
  (atom
  {:people/by-id {1 {:id 1 :name "Bob"} 2 {:id 2 :name "Jane"}}
   :departments/by-id {0 {:name "Software" :people #{} :id 0}
                       1 {:name "Marketing" :people #{} :id 1}
                       2 {:name "HR" :people #{[:people/by-id 1] [:people/by-id 2]} :id 2}}}))
```

Using Reagent's [track ](https://reagent-project.github.io/news/news060-alpha.html) I could get a materialised view into the departments, meaning that they'd have the actual employee data and not just the idents, by first defining a function something like this:

```
(defn materialised-departments [atom]
  (map
    (fn [dept]
      (assoc dept :people
                  (set (map
                         (fn [emp-q]
                           (get-in @atom emp-q))
                         (:people dept)))))
    (vals (get-in @atom [:departments/by-id]))))
```

Then I would use the above function with r/track, to create a materialised view of the departments. My components will handle it just like a normal ratom, and react to its changes.

```
(let [departments (r/track model/materialised-departments atom)])
```

Rum (like Reagent) has `cursor`, but I don't know if it can be used to accomplish something like this. Honestly, I'm not sure if this issue is a support request / question, or a valid feature request. I'd be happy to hear your thoughts on this!

**Comment by niwinz** [comment]
As I have comented on clojurians slack, it seems like a support question that an issue. And I suggest take a look at http://funcool.github.io/lentes/latest/ that I think that it solves your problem.

**Comment by tonsky** [comment]
I figured it is indeed a common use-case, to have dependent values and to react to them. Moreover, Rum already provides couple of tools to work with atoms: cursors, reactive mixin. So in 0.9.1 I’ve added `derived-atom`, a facility to build reactive chains and DAGs of dependent atoms

Docs are here https://github.com/tonsky/rum/blob/gh-pages/src/rum/util.cljc
But use it through `rum.core/derived-atom`
