### ISSUE TITLE
ReactDOM.unstable_batchedUpdates breaks ReactNative

### ISSUE THREAD

**Issue by dukefong8** [tonsky/rum#77]
Hi,

Rum works really well in re-natal w/ react-native. However, recent (unreleased) change "Do all re-renders on requestAnimationFrame in a single batch" breaks it. The same is available in react native though.

https://github.com/facebook/react-native/blob/803cb61346bcdf85d68df5cdfc1a392f78e6cac3/Libraries/react-native/react-native.js#L156

I did a workaround like this. It works. Maybe there could be a better way rum can support.

(set! js/window.ReactDOM (js/require "react-native"))

Thanks

**Comment by tonsky** [comment]
Hi @FongHou ! It’s so great you were able to test pre-release version of Rum. It’s also awesome you’re using it for ReactNative. In fact, I’d love to hear more about your experience with it. I’d like to support RN one day in Rum. Do you need to change a lot? Is it working as-is?

Regarding your problem, would something like that work?

``` clj
(def ^:private batch
  (if (exists? js/ReactNative)
    js/ReactNative.unstable_batchedUpdates
    js/ReactDOM.unstable_batchedUpdates))
...
(defn- render []
  (let [queue @render-queue]
    (vreset! render-queue empty-queue)
    (batch render-all queue)))
```

**Comment by dukefong8** [comment]
Hi @tonsky, I just checked out master. It works great! Thanks!

Rum actually works out of box as-is thanks to the awesome work from re-natal folks. For me, it's definitely _the_ best workflow and environment for learning and/or prototyping mobile app.

Only thing that has to be excluded is sablono because of ReactDOM like this.

`[rum "0.9.1" :exclusions [cljsjs/react cljsjs/react-dom sablono]]]`

And define react comp factory functions as below.

```
(defn create-element [rn-comp opts & children]
  (apply js/React.createElement rn-comp (clj->js opts) children))

(def ReactNative (js/require "react-native"))
(def app-registry (.-AppRegistry ReactNative))
(def view (partial create-element (.-View ReactNative)))
(def text (partial create-element (.-Text ReactNative)))
(def text-input (partial create-element (.-TextInput ReactNative)))
(def list-view (partial create-element (.-ListView ReactNative)))
... 
```

In case you'd like to add some macro helper for above boilerplate  (btw, I don't miss sablono that much as it's very DOM centric. Maybe a sepearte shorthand syntax for flexbox css?)

Regards

**Comment by tonsky** [comment]
I’ll try to figure out the best way to use Rum in both DOM and RN
environments, taking into account your advice. I’m very eager to try it out
for mobile development—the only problem being finding a free time for that
:(
