### ISSUE TITLE
Indentation support for Emacs

### ISSUE THREAD

**Issue by chrisetheridge** [tonsky/rum#80]
**Problem**

In emacs, the mixin macro does not get indented properly. You have to either write your components like this:

``` clj
(rum/defc text [] < rum/reactive (rum/local "" ::text) ...)
```

Or, like this:

``` clj
(rum/defc text [] < rum/reactive
  (rum/local "" ::text)
...)
```

This unfortunately is not pleasing to the eye at all, and can get confusing very quickly as you add more mixins to your component.

**Proposed solution**

The Emacs plugin, [cider](https://github.com/clojure-emacs/cider), allows you to specify how it should indent a function or macro. You can read about that [here](https://cider.readthedocs.io/en/latest/indent_spec/). Adding this to `rum` would be incredibly helpful!

**Comment by tonsky** [comment]
I don’t use Emacs, but don’t mind that change if you provide a PR

**Comment by chrisetheridge** [comment]
Sure! I will see what I can do :-)

**Comment by chrisetheridge** [comment]
Unfortunately cider cannot support this type of indentation :/ Closing.
