### ISSUE TITLE
Server side rendering requires Sablono and transitively Clojurescript.

### ISSUE THREAD

**Issue by prathyvsh** [tonsky/rum#83]
Posting as requested on Twitter: http://twitter.com/prathyvsh/status/750641432386367489

Using rum.core/render-static-markup solely for server side rendering leads to import of Clojurescript.
Excluding Clojurescript is a no go since Sablono is being pulled in on the core ns.

This can be remedied by using
`[rum "0.10.3" :only [server-render]]`
on import.

But a better solution could be out there.

**Comment by tonsky** [comment]
Fixed in 0.11.1
