### ISSUE TITLE
Better feedback when mixing argvec/mixin order

### ISSUE THREAD

**Issue by martinklepsch** [tonsky/rum#88]
It has happened to me a few times now that I got stuck because I put the mixin in the wrong place.

```
(defc x
  [a b]
  < rum/static
  [:div "bla"])
```

I think this is something that could be improved to give better feedback.
While throwing an exception isn't guaranteed to be correct the probability of false positives seems low (i.e. component bodies starting with a plain `<`). 

Would you be interested in a patch that throws for the above snippet? Do you have alternative suggestions that might be less absolute?

Maybe throwing an exception is a good first step and can be revisited once there is some user feedback.

**Comment by tonsky** [comment]
I think it’s a good idea, yes
