### ISSUE TITLE
why schedule render when render-queue is empty

### ISSUE THREAD

**Issue by dukefong8** [tonsky/rum#89]
https://github.com/tonsky/rum/blob/gh-pages/src/rum/core.cljs#L180

Shouldn't it be the other way around, i.e. 

```
(defn request-render
  "Schedules react component to be rendered on next animation frame"
  [component]
  (when (seq @render-queue)
    (schedule render))
  (vswap! render-queue conj component))
```

Cheers!

**Comment by dukefong8** [comment]
Closing this because that'll miss events.

**Comment by tonsky** [comment]
The purpose of checking for empty? is to make sure we schedule only once per animation frame

**Comment by dukefong8** [comment]
Got it. So the logic is that empty render-queue is the demarcation between animation frames. Thank you for the hint! 

Cheers!
