### ISSUE TITLE
Sharing more examples

### ISSUE THREAD

**Issue by mdhaney** [tonsky/rum#9]
Based on my work of porting my app to Rum, I would like to extract some of the mix-ins I have created into stand alone examples people can refer to.  I would like your input on how best to share this work with the community.

Some possibilities:

1) series of Gists that you can link to from the README if you choose
2) pages in the Wiki (maybe a Rum Cookbook, like they are doing for Reagent)
3) add to the examples in the project repo

Do you have a preference?

**Comment by tonsky** [comment]
Cool! I think, let’s start with wiki
