### ISSUE TITLE
Server/client render checksum invalid

### ISSUE THREAD

**Issue by visibletrap** [tonsky/rum#91]
Could you have a look at this repo https://github.com/visibletrap/rum-issue? I got invalid checksum error with a simple template like

``` clj
(rum/defc my-comp []
  [:div [:div]])
```

**Comment by visibletrap** [comment]
Tag previous checksum invalid issue https://github.com/tonsky/rum/issues/67

**Comment by tonsky** [comment]
You should render into a component that's one level above of `[data-reactroot]`. The component is mounted _inside_ the element you pass into `mount`

**Comment by tonsky** [comment]
I've fixed that in README too

**Comment by visibletrap** [comment]
Thanks @tonsky
