### ISSUE TITLE
Sharing state from root to all nested components

### ISSUE THREAD

**Issue by alvinfrancis** [tonsky/rum#95]
In Om, mounting the component root with `om/root` also allows for supplying shared state which can then be accessed by any component under the root component via `om/get-shared`. This allows for global data and services to be set without resorting to global state since all state is still local to the mounted component tree. This allows, for example, multiple mounts of the same app on the same page with "global" data and services independent from each other.

Would it be possible to include something similar to rum? Or are there any suggested patterns to get the same result?

**Comment by ghost** [comment]
> Or are there any suggested patterns to get the same result?

React's [context](https://facebook.github.io/react/docs/context.html) feature solves that problem, although i don't have an example of using it from Rum.

**Comment by martinklepsch** [comment]
My derivatives library linked in the Rum Readme exports some of its
functionality via component context if you are curious.

**Comment by ghost** [comment]
Here is the [relevant source code](https://github.com/martinklepsch/derivatives/blob/6302772b705f53e07a8dd58e7f1826462f9a5f44/src/org/martinklepsch/derivatives.cljc#L101-L110). Didn't know about `derivatives`, cool project!

**Comment by alvinfrancis** [comment]
Thanks for all the help guys.  Looks like context is exactly what I need.  I can build my abstractions over that.  Thanks for linking that source as well.  I'll be studying it.

Closing this issue.
