### ISSUE TITLE
Error/warning when unrecognised keys are passed in mixin

### ISSUE THREAD

**Issue by martinklepsch** [tonsky/rum#96]
If people have a typo in their mixin keys things will silently fail. Would you be open to a PR that logs a warning or similar when an unknown key is passed as part of a mixin map?

**Comment by tonsky** [comment]
I’d say more: we should leverage schema for that, probably. At least after 1.9 is out of the door

**Comment by martinklepsch** [comment]
Not sure about intrusions a dependency (schema or spec for that matter) for
this particular thing but great that you're also on board about making that
a little better :)

(I know spec isn't really a dependency but it's still somewhat alpha, might
have unexpected effects on code size etc so I'm more in favor of a simple
subset check)
