### ISSUE TITLE
Client vs server rendering results in React warning: checksum invalid

### ISSUE THREAD

**Issue by fotoetienne** [tonsky/rum#99]
There is a slight difference in server vs client side rendering which is causing a React warning:

```
react.inc.js:20541Warning: React attempted to reuse markup in a container
but the checksum was invalid. This generally means that you are using server
rendering and the markup generated on the server was not what the client was
expecting. React injected new markup to compensate which works but you have
lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:

(client) lass="pure-menu-item " data-reactid="12"
(server) lass="pure-menu-item" data-reactid="12">
```

Note the space following `pure-menu-item` in the client side version.

The relevant code section:

```
(defc nav-item < rum/reactive [item]
  [:div
  {:on-click (fn [_] (update-selected! :feature (lower-case item)))}
  [:li.pure-menu-item
    {:class (when (= (:feature (rum/react selected)) (lower-case item))
              "pure-menu-selected")}
    [:a.pure-menu-link {:href "#"} item]]])
```

This can be fixed by removing `.pure-menu-item` from the `:li`, so it could be considered either a bug or user error. It seems it would be better for the client rendering to trim the trailing space.

Btw, loving rum. Thanks for the hard work.
-Stephen

**Comment by tonsky** [comment]
Wow that one is actually pretty tricky.

```
[:.c1 { :class nil }]
```

will render as `<div class="c1"></div>`, but

```
[:.c1 { :class (when false "...") }]
```

will render as `<div class="c1 "></div>`

I know it’s Sablono’s pre-compilation messes things up, but I have no way to emulate that on a server at the moment :( I was planning to unify attribute parsing/macro pre-compilation and get rid of Sablono in the future, then it won’t be an issue. Until then, you have to look for workarounds

**Comment by fotoetienne** [comment]
I figured that it would require a Sablono change.

For posterity, the work-around isn't too bad. This works fine:

```
(defc nav-item < rum/reactive [item]
  [:div
  {:on-click (fn [_] (update-selected! :feature (lower-case item)))}
  [:li
    {:class (str "pure-menu-item"
                (when (= (:feature (rum/react selected)) (lower-case item))
                  " pure-menu-selected"))}
    [:a.pure-menu-link {:href "#"} item]]])
```

**Comment by rauhs** [comment]
I think sablono should be fixed:

`(sablono.util/join-classes ["c1" nil])`

The `map` in `join-classes` should probably be changed to `keep`.

**Comment by tonsky** [comment]
Try 0.10.7, should be fixed now

**Comment by fotoetienne** [comment]
🎉 Thanks!
